import { API_BASE_URL } from '../constants/api';

export interface TransactionToJournalRequest {
  transactionId: number;
  companyId?: string;
  forceRegenerate?: boolean;
}

export interface JournalEntryDetail {
  id?: number;
  lineNumber: number;
  accountCode: string;
  accountName: string;
  debitAmount: number;
  creditAmount: number;
  description: string;
}

export interface JournalEntry {
  id: number;
  companyId: string;
  entryDate: string;
  description: string;
  referenceType: string;
  referenceId: number;
  totalAmount: number;
  status: 'DRAFT' | 'CONFIRMED' | 'POSTED';
  autoGenerated: boolean;
  confidence: number;
  details: JournalEntryDetail[];
  createdAt: string;
  updatedAt: string;
}

export interface JournalEntryResponse {
  success: boolean;
  journalEntry?: JournalEntry;
  validation?: {
    isValid: boolean;
    balanceCheck: string;
    errorMessages: string[];
  };
  processingInfo?: {
    processingTimeMs: number;
    method: string;
    ruleSource: string;
  };
  message?: string;
  error?: string;
}

export interface ChartOfAccount {
  id: number;
  accountCode: string;
  accountName: string;
  accountType: 'ASSET' | 'LIABILITY' | 'EQUITY' | 'REVENUE' | 'EXPENSE';
  accountSubtype: string;
  isDebitNormal: boolean;
  parentAccountId?: number;
  isActive: boolean;
  displayOrder: number;
}

class BookkeepingService {
  /**
   * 거래를 분개로 변환
   */
  static async generateJournalEntry(request: TransactionToJournalRequest): Promise<JournalEntryResponse> {
    try {
      const response = await fetch(`${API_BASE_URL}/api/v2/accounting/process-transaction`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(request),
      });

      const data = await response.json();

      if (!response.ok) {
        return {
          success: false,
          message: data.message || '분개 생성 중 오류가 발생했습니다.',
          error: data.error
        };
      }

      return data;
    } catch (error) {
      console.error('분개 생성 API 호출 오류:', error);
      return {
        success: false,
        message: '네트워크 오류가 발생했습니다.',
        error: error instanceof Error ? error.message : 'Unknown error'
      };
    }
  }

  /**
   * 분개 상세 조회
   */
  static async getJournalEntry(journalEntryId: number): Promise<JournalEntry | null> {
    try {
      const response = await fetch(`${API_BASE_URL}/api/v2/accounting/journal-entry/${journalEntryId}`, {
        method: 'GET',
        headers: {
          'Content-Type': 'application/json',
        },
      });

      if (!response.ok) {
        if (response.status === 404) {
          return null;
        }
        throw new Error(`분개 조회 실패: ${response.status}`);
      }

      return await response.json();
    } catch (error) {
      console.error('분개 조회 오류:', error);
      throw error;
    }
  }

  /**
   * 분개 목록 조회
   */
  static async getJournalEntries(
    companyId: string,
    startDate: string,
    endDate: string
  ): Promise<JournalEntry[]> {
    try {
      const params = new URLSearchParams({
        companyId,
        startDate,
        endDate
      });

      const response = await fetch(`${API_BASE_URL}/api/v2/accounting/journal-entries?${params}`, {
        method: 'GET',
        headers: {
          'Content-Type': 'application/json',
        },
      });

      if (!response.ok) {
        throw new Error(`분개 목록 조회 실패: ${response.status}`);
      }

      return await response.json();
    } catch (error) {
      console.error('분개 목록 조회 오류:', error);
      throw error;
    }
  }

  /**
   * 계정과목 목록 조회
   */
  static async getChartOfAccounts(): Promise<ChartOfAccount[]> {
    try {
      const response = await fetch(`${API_BASE_URL}/api/v2/accounting/chart-of-accounts`, {
        method: 'GET',
        headers: {
          'Content-Type': 'application/json',
        },
      });

      if (!response.ok) {
        throw new Error(`계정과목 조회 실패: ${response.status}`);
      }

      return await response.json();
    } catch (error) {
      console.error('계정과목 조회 오류:', error);
      throw error;
    }
  }

  /**
   * 분개 수정
   */
  static async updateJournalEntry(journalEntryId: number, updatedEntry: Partial<JournalEntry>): Promise<JournalEntryResponse> {
    try {
      const response = await fetch(`${API_BASE_URL}/api/v2/accounting/journal-entry/${journalEntryId}`, {
        method: 'PUT',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(updatedEntry),
      });

      const data = await response.json();

      if (!response.ok) {
        return {
          success: false,
          message: data.message || '분개 수정 중 오류가 발생했습니다.',
          error: data.error
        };
      }

      return {
        success: true,
        journalEntry: data
      };
    } catch (error) {
      console.error('분개 수정 오류:', error);
      return {
        success: false,
        message: '네트워크 오류가 발생했습니다.',
        error: error instanceof Error ? error.message : 'Unknown error'
      };
    }
  }

  /**
   * 분개 상태 변경 (승인/확정)
   */
  static async confirmJournalEntry(journalEntryId: number): Promise<JournalEntryResponse> {
    try {
      const response = await fetch(`${API_BASE_URL}/api/v2/accounting/journal-entries/${journalEntryId}/confirm`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
      });

      const data = await response.json();

      if (!response.ok) {
        return {
          success: false,
          message: data.message || '분개 승인 중 오류가 발생했습니다.',
          error: data.error
        };
      }

      return {
        success: true,
        journalEntry: data
      };
    } catch (error) {
      console.error('분개 승인 오류:', error);
      return {
        success: false,
        message: '네트워크 오류가 발생했습니다.',
        error: error instanceof Error ? error.message : 'Unknown error'
      };
    }
  }

  /**
   * 분개 대차평균 검증
   */
  static validateJournalEntry(journalEntry: JournalEntry): {
    isBalanced: boolean;
    totalDebit: number;
    totalCredit: number;
    errors: string[];
  } {
    const errors: string[] = [];
    
    if (!journalEntry.details || journalEntry.details.length === 0) {
      errors.push('분개 상세가 없습니다.');
      return { isBalanced: false, totalDebit: 0, totalCredit: 0, errors };
    }

    if (journalEntry.details.length < 2) {
      errors.push('분개는 최소 2개 라인이 필요합니다.');
    }

    const totalDebit = journalEntry.details.reduce((sum, detail) => sum + detail.debitAmount, 0);
    const totalCredit = journalEntry.details.reduce((sum, detail) => sum + detail.creditAmount, 0);

    const isBalanced = totalDebit === totalCredit;
    
    if (!isBalanced) {
      errors.push(`차변 합계(₩${totalDebit.toLocaleString()})와 대변 합계(₩${totalCredit.toLocaleString()})가 일치하지 않습니다.`);
    }

    if (totalDebit !== journalEntry.totalAmount) {
      errors.push(`분개 총액(₩${journalEntry.totalAmount.toLocaleString()})과 차변 합계(₩${totalDebit.toLocaleString()})가 일치하지 않습니다.`);
    }

    // 각 라인별 검증
    journalEntry.details.forEach((detail, index) => {
      const hasDebit = detail.debitAmount > 0;
      const hasCredit = detail.creditAmount > 0;

      if (hasDebit && hasCredit) {
        errors.push(`라인 ${index + 1}: 차변과 대변 금액이 동시에 있을 수 없습니다.`);
      }

      if (!hasDebit && !hasCredit) {
        errors.push(`라인 ${index + 1}: 차변 또는 대변 중 하나의 금액이 있어야 합니다.`);
      }
    });

    return {
      isBalanced: isBalanced && errors.length === 0,
      totalDebit,
      totalCredit,
      errors
    };
  }

  /**
   * 시스템 상태 확인
   */
  static async checkHealth(): Promise<{ status: string; healthy: boolean }> {
    try {
      const response = await fetch(`${API_BASE_URL}/api/v2/accounting/health`, {
        method: 'GET',
        headers: {
          'Content-Type': 'application/json',
        },
      });

      const data = await response.json();

      return {
        status: data.status || 'unknown',
        healthy: response.ok && data.status === 'healthy'
      };
    } catch (error) {
      console.error('헬스체크 오류:', error);
      return {
        status: 'error',
        healthy: false
      };
    }
  }
}

export default BookkeepingService;