-- JSON 패턴을 정규식 규칙으로 변환 (588개)
-- 생성 시간: 2025-07-27T22:26:09.598Z

-- 기존 중복 방지를 위한 임시 테이블 생성
CREATE TEMP TABLE temp_new_rules AS
SELECT 
  pattern,
  replacement,
  category,
  description,
  priority,
  true as is_active,
  NOW() as created_at,
  NOW() as updated_at,
  metadata
FROM (VALUES
  ('(스시|초밥|회전초밥|SUSHI|すし|寿司)', '일식당', '음식점', '스시/초밥 일반 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(스시로|스시잔마이|스시노미도리|스시효|스시쿠이네)', '일식당', '음식점', '스시 전문 브랜드 패턴', 90, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.9}'::jsonb),
  ('(갓덴스시|상무초밥|초밥천국|스시웨이|스시박스)', '일식당', '음식점', '국내 스시 프랜차이즈 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(오마카세|おまかせ|OMAKASE|셰프스초이스)', '일식당', '음식점', '오마카세 전문점 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(사시미|さしみ|刺身|생선회|활어회)', '일식당', '음식점', '사시미/회 전문점 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(라멘|라면|ラーメン|拉麺|RAMEN)', '일식당', '음식점', '라멘 일반 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(이치란|잇푸도|멘야산다이메|킷카타|하카타분코)', '일식당', '음식점', '라멘 전문 브랜드 패턴', 90, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.9}'::jsonb),
  ('(돈코츠|돈코쓰|豚骨|미소|된장|시오|소금|쇼유|간장)', '일식당', '음식점', '라멘 종류별 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(츠케멘|つけ麺|마제소바|아부라소바|탄탄멘)', '일식당', '음식점', '특수 라멘 종류 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(우동|うどん|UDON|사누키우동|가케우동)', '일식당', '음식점', '우동 전문점 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(마루가메제면|니쿠우동|역전우동|우동신|우동마루)', '일식당', '음식점', '우동 프랜차이즈 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(소바|そば|蕎麦|SOBA|메밀국수|자루소바)', '일식당', '음식점', '소바 전문점 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(돈까스|돈카츠|とんかつ|TONKATSU|돈가스)', '일식당', '음식점', '돈까스 일반 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(사보텐|카츠야|마이센|기소야|카츠&)', '일식당', '음식점', '돈까스 전문 브랜드 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(경양식|일본식돈까스|왕돈까스|치즈돈까스|카레돈까스)', '일식당', '음식점', '돈까스 변형 메뉴 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(카츠동|카츠돈|かつ丼|가츠동|돈까스덮밥)', '일식당', '음식점', '카츠동 전문점 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(규동|규돈|牛丼|GYUDON|소고기덮밥)', '일식당', '음식점', '규동 전문점 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(요시노야|스키야|마츠야|나카우|규동전문)', '일식당', '음식점', '규동 체인점 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(덮밥|돈부리|どんぶり|DONBURI|일본덮밥)', '일식당', '음식점', '덮밥 일반 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(오야코동|親子丼|텐동|天丼|우나동|うな丼)', '일식당', '음식점', '특수 덮밥 종류 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(이자카야|居酒屋|IZAKAYA|일본술집|일본선술집)', '일식당', '음식점', '이자카야 일반 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(와라와라|츠보하치|토리돈|야키토리|꼬치구이)', '일식당', '음식점', '이자카야 브랜드 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(사케|日本酒|니혼슈|청주|일본술)', '일식당', '음식점', '일본술 전문점 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(야키니쿠|焼肉|YAKINIKU|일본식구이|화로구이)', '일식당', '음식점', '야키니쿠 전문점 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(규카츠|규가츠|牛カツ|소고기카츠|비프카츠)', '일식당', '음식점', '규카츠 전문점 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(텐푸라|덴뿌라|天ぷら|TEMPURA|튀김정식)', '일식당', '음식점', '텐푸라 전문점 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(장어|우나기|うなぎ|UNAGI|장어구이|장어덮밥)', '일식당', '음식점', '장어 전문점 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(스키야키|すき焼き|SUKIYAKI|일본식전골|샤브샤브)', '일식당', '음식점', '스키야키/샤브샤브 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(나베|鍋|NABE|일본전골|일본식찌개)', '일식당', '음식점', '나베 요리 전문점 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(벤토|弁当|BENTO|도시락|일본도시락)', '일식당', '음식점', '일본식 도시락 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(오코노미야키|お好み焼き|타코야키|たこ焼き|일본전)', '일식당', '음식점', '오코노미야키/타코야키 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(카레|카레라이스|カレー|CURRY|일본카레)', '일식당', '음식점', '일본 카레 전문점 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(코코이찌방야|CoCo壱番屋|아비꼬|카레신)', '일식당', '음식점', '카레 전문 브랜드 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(미소시루|味噌汁|일본국|일본된장국)', '일식당', '음식점', '일본 국/찌개 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(정식|定食|TEISHOKU|일본정식|일식정식)', '일식당', '음식점', '일본 정식 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(야마야|오오토야|혼케츠루하시|후라토식당)', '일식당', '음식점', '일본 정식당 브랜드 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(모찌|떡|もち|MOCHI|일본떡)', '일식당', '음식점', '일본 떡/디저트 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(와규|和牛|WAGYU|일본소|일본한우)', '일식당', '음식점', '와규 전문점 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(참치|마구로|まぐろ|TUNA|참치전문)', '일식당', '음식점', '참치 전문점 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(연어|사케|サケ|SALMON|연어전문)', '일식당', '음식점', '연어 전문점 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(카이센동|海鮮丼|해산물덮밥|회덮밥)', '일식당', '음식점', '카이센동 전문점 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(치라시|ちらし|CHIRASHI|치라시스시|흩뿌림초밥)', '일식당', '음식점', '치라시 전문점 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(마키|巻き|MAKI|김밥초밥|롤초밥)', '일식당', '음식점', '마키/롤 전문점 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(니기리|握り|NIGIRI|쥔초밥|손초밥)', '일식당', '음식점', '니기리 전문점 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(가이세키|懐石|KAISEKI|일본코스요리|고급일식)', '일식당', '음식점', '가이세키 요리 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(로바타야키|炉端焼|화로구이|일본숯불구이)', '일식당', '음식점', '로바타야키 전문점 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(멘타이코|明太子|명란|명란젓|멘타이)', '일식당', '음식점', '멘타이코 요리 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(에비|海老|새우튀김|새우카츠|에비후라이)', '일식당', '음식점', '새우 요리 전문점 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(일본가정식|일본집밥|오카상|엄마손맛|일본홈쿠킹)', '일식당', '음식점', '일본 가정식 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(중식|중국집|중화요리|중국요리|중국음식|차이나푸드)', '중식당', '음식점', '중식당 일반 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(짜장면|자장면|짜장|자장|炸醬麵|JJAJANGMYEON)', '중식당', '음식점', '짜장면 관련 패턴', 90, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.9}'::jsonb),
  ('(짬뽕|챰뽕|짬봉|짬뽕밥|JJAMPPONG|炒碼麵)', '중식당', '음식점', '짬뽕 관련 패턴', 90, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.9}'::jsonb),
  ('(탕수육|탕슉|糖醋肉|TANGSUYUK|꿔바로우|锅包肉)', '중식당', '음식점', '탕수육 관련 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(마라탕|麻辣燙|MALATANG|마라샹궈|마라훠궈)', '중식당', '음식점', '마라탕/마라 요리 패턴', 90, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.9}'::jsonb),
  ('(탕화쿵푸|미스터짬뽕|홍콩반점|북경|베이징)', '중식당', '음식점', '중식 프랜차이즈 브랜드 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(진짜루|백짬뽕|역전우동0410중화|만리성|대만왕)', '중식당', '음식점', '국내 중식 체인점 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(간짜장|쟁반짜장|유니짜장|삼선짜장|사천짜장)', '중식당', '음식점', '짜장면 종류별 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(백짬뽕|삼선짬뽕|차돌짬뽕|해물짬뽕|고추짬뽕)', '중식당', '음식점', '짬뽕 종류별 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(볶음밥|炒飯|FRIEDRICE|새우볶음밥|짬뽕밥|짜장밥)', '중식당', '음식점', '볶음밥 관련 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(군만두|물만두|찐만두|교자|딤섬|点心)', '중식당', '음식점', '만두/딤섬 관련 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(춘권|春卷|스프링롤|SPRINGROLL|하르방)', '중식당', '음식점', '춘권 관련 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(훠궈|火鍋|HOTPOT|샤브샤브|중국식전골)', '중식당', '음식점', '훠궈/중국 전골 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(하이디라오|海底撈|HAIDILAO|샤오룽칸|小龙坎)', '중식당', '음식점', '훠궈 전문 브랜드 패턴', 90, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.9}'::jsonb),
  ('(양꼬치|양고기|羊肉串|양갈비|연태|칭다오)', '중식당', '음식점', '양꼬치/양고기 전문점 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(마파두부|麻婆豆腐|MAPOTOFU|사천요리|四川)', '중식당', '음식점', '사천요리 관련 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(깐풍기|깐풍육|乾烹|간풍|깐풍새우)', '중식당', '음식점', '깐풍 요리 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(팔보채|八宝菜|잡채밥|중화잡채|해물잡채)', '중식당', '음식점', '팔보채/잡채 관련 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(유산슬|油三絲|중화냉채|겨자냉채|냉채)', '중식당', '음식점', '중화 냉채 요리 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(난자완스|南煎丸子|동파육|東坡肉|중국식미트볼)', '중식당', '음식점', '중국 육류 요리 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(샤오마이|소룡포|小籠包|XIAOLONGBAO|만두전문)', '중식당', '음식점', '소룡포/만두 전문점 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(딘타이펑|鼎泰豊|DINTAIFUNG|남상창|南翔)', '중식당', '음식점', '딤섬 전문 브랜드 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(북경오리|베이징덕|北京烤鴨|PEKINGDUCK|오리구이)', '중식당', '음식점', '북경오리 전문점 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(크리스피덕|취영루|全聚德|쥐안쥐더)', '중식당', '음식점', '북경오리 브랜드 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(중식뷔페|중국뷔페|중화뷔페|무한리필중식)', '중식당', '음식점', '중식 뷔페 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(칠리새우|깐쇼새우|중화새우|왕새우요리)', '중식당', '음식점', '새우 요리 전문 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(멘보샤|面包虾|토스트새우|새우토스트)', '중식당', '음식점', '멘보샤 관련 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(라조기|라조육|辣椒|고추잡채|사천식고추)', '중식당', '음식점', '라조 요리 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(중국냉면|중화냉면|비빔냉면|사천냉면)', '중식당', '음식점', '중국식 냉면 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(울면|기스면|간짜면|짜장라면|중화라면)', '중식당', '음식점', '특수 면요리 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(동북|둥베이|東北|연변|조선족)', '중식당', '음식점', '동북/연변 요리 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(꿔티에|鍋貼|군만두|구운만두|팬프라이만두)', '중식당', '음식점', '꿔티에/구운만두 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(가지튀김|어향가지|魚香茄子|중화가지)', '중식당', '음식점', '가지 요리 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(중국식볶음|웍|WOK|불맛|화구)', '중식당', '음식점', '중식 볶음 요리 일반 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(월병|月餅|중국과자|중국떡|중화디저트)', '중식당', '음식점', '중국 디저트 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(중국차|중차|茶|우롱차|보이차|철관음)', '중식당', '음식점', '중국차 전문점 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(광동요리|広東|광둥|딤섬전문|얌차)', '중식당', '음식점', '광동요리 전문점 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(상해요리|上海|샹하이|상하이|강남요리)', '중식당', '음식점', '상해요리 전문점 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(산동요리|山東|산둥|교동반점|만물상)', '중식당', '음식점', '산동요리 전문점 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(쿵파오치킨|宮保鶏丁|궁보계정|땅콩닭)', '중식당', '음식점', '쿵파오치킨 관련 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(중국술|백주|白酒|마오타이|연태고량주)', '중식당', '음식점', '중국술 전문점 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(중화비빔밥|중국덮밥|마파덮밥|짜사이덮밥)', '중식당', '음식점', '중국식 덮밥 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(탄탄면|担担麺|DANDAN|중국비빔면|사천비빔면)', '중식당', '음식점', '탄탄면 관련 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(전가복|全家福|중화모듬|스페셜요리|중화특선)', '중식당', '음식점', '중화 특선요리 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(게살스프|계란탕|중국스프|상어지느러미)', '중식당', '음식점', '중국식 스프 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(중화오믈렛|계란요리|중국식계란|푸용하이)', '중식당', '음식점', '중국식 계란요리 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(중국가정식|중화가정식|집밥중식|중국엄마)', '중식당', '음식점', '중국 가정식 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(우육면|牛肉麺|중국우육면|란저우라면)', '중식당', '음식점', '우육면 전문점 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(중화포차|중국포차|마라포차|중국야시장)', '중식당', '음식점', '중국식 포차/야시장 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(한식|한식당|한식집|한국음식|한국요리|KOREAN)', '한식당', '음식점', '한식당 일반 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(국밥|국밥집|순대국|돼지국밥|소머리국밥|뼈해장국)', '한식당', '음식점', '국밥류 전문점 패턴', 90, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.9}'::jsonb),
  ('(하동관|신선설농탕|명동교자|을밀대|진주회관)', '한식당', '음식점', '전통 한식당 브랜드 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(본죽|죽이야기|팥죽|호박죽|전복죽|야채죽)', '한식당', '음식점', '죽 전문점 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(찌개|김치찌개|된장찌개|순두부찌개|부대찌개|찌개백반)', '한식당', '음식점', '찌개 전문점 패턴', 90, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.9}'::jsonb),
  ('(백반|정식|한정식|백반집|가정식백반|집밥)', '한식당', '음식점', '백반/정식 전문점 패턴', 90, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.9}'::jsonb),
  ('(비빔밥|전주비빔밥|돌솥비빔밥|육회비빔밥|산채비빔밥)', '한식당', '음식점', '비빔밥 전문점 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(한식뷔페|한정식뷔페|뷔페식당|무한리필한식)', '한식당', '음식점', '한식 뷔페 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(삼계탕|백숙|토종닭|닭백숙|인삼삼계탕|영계백숙)', '한식당', '음식점', '삼계탕/백숙 전문점 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(곰탕|설렁탕|갈비탕|우거지탕|사골국|꼬리곰탕)', '한식당', '음식점', '탕류 전문점 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(감자탕|뼈해장국|뼈다귀|감자국|등뼈찜)', '한식당', '음식점', '감자탕 전문점 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(24시|이십사시|24시간|새벽식당|올나잇)', '한식당', '음식점', '24시 한식당 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(콩나물국밥|콩나물해장국|전주콩나물|남원추어탕|추어탕)', '한식당', '음식점', '해장국 전문점 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(보쌈정식|수육백반|보쌈백반|김치보쌈|막국수보쌈)', '한식당', '음식점', '보쌈정식 전문점 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(쌈밥|쌈밥정식|쌈채소|야채쌈밥|고기쌈밥)', '한식당', '음식점', '쌈밥 전문점 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(제육볶음|제육백반|두루치기|김치제육|매운제육)', '한식당', '음식점', '제육볶음 전문점 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(불고기|불고기백반|불고기정식|한우불고기|돼지불고기)', '한식당', '음식점', '불고기 전문점 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(생선구이|고등어구이|갈치구이|조기구이|생선백반)', '한식당', '음식점', '생선구이 전문점 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(냉면|물냉면|비빔냉면|평양냉면|함흥냉면|막국수)', '한식당', '음식점', '냉면 전문점 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(육개장|육계장|대구탕|매운탕|알탕|알찌개)', '한식당', '음식점', '매운탕류 전문점 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(청국장|청국장찌개|낫토찌개|구수한집)', '한식당', '음식점', '청국장 전문점 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(갈비찜|찜갈비|소갈비찜|돼지갈비찜|매운갈비찜)', '한식당', '음식점', '갈비찜 전문점 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(아구찜|아귀찜|해물찜|꽃게찜|대게찜)', '한식당', '음식점', '해물찜 전문점 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(닭갈비|춘천닭갈비|철판닭갈비|닭갈비볶음밥)', '한식당', '음식점', '닭갈비 전문점 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(찜닭|안동찜닭|간장찜닭|매운찜닭|치즈찜닭)', '한식당', '음식점', '찜닭 전문점 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(닭볶음탕|닭도리탕|매운닭|춘천통닭|닭한마리)', '한식당', '음식점', '닭볶음탕 전문점 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(오리탕|오리주물럭|오리로스|훈제오리|오리백숙)', '한식당', '음식점', '오리 요리 전문점 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(전골|김치전골|부대전골|곱창전골|버섯전골)', '한식당', '음식점', '전골 전문점 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(순대|순댓국|순대볶음|순대정식|암뽕순대)', '한식당', '음식점', '순대 전문점 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(해장국|선지해장국|우거지해장국|북어해장국|황태해장국)', '한식당', '음식점', '해장국 전문점 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(칼국수|손칼국수|바지락칼국수|들깨칼국수|김치칼국수)', '한식당', '음식점', '칼국수 전문점 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(수제비|감자수제비|김치수제비|해물수제비|옹심이)', '한식당', '음식점', '수제비 전문점 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(보리밥|산채비빔밥|나물밥|영양돌솥밥|곤드레밥)', '한식당', '음식점', '건강식 한식당 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(떡갈비|떡갈비정식|화양떡갈비|담양떡갈비|한우떡갈비)', '한식당', '음식점', '떡갈비 전문점 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(편육|수육|돼지수육|보쌈수육|막걸리집)', '한식당', '음식점', '편육/수육 전문점 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(두부|두부전골|두부김치|순두부|모두부)', '한식당', '음식점', '두부 요리 전문점 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(장어구이|민물장어|풍천장어|장어정식|장어탕)', '한식당', '음식점', '장어구이 전문점 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(막창|곱창구이|대창구이|양구이|특양구이)', '한식당', '음식점', '곱창구이 전문점 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(전|파전|김치전|해물파전|동그랑땡|전집)', '한식당', '음식점', '전 전문점 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(묵|도토리묵|메밀묵|묵밥|묵사발|묵무침)', '한식당', '음식점', '묵 요리 전문점 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(나물|산나물|나물정식|산채정식|약선요리)', '한식당', '음식점', '나물/산채 전문점 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(궁중요리|한정식|고급한정식|전통한정식|코스요리)', '한식당', '음식점', '궁중/고급 한정식 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(사찰음식|절밥|템플푸드|비건한식|채식한정식)', '한식당', '음식점', '사찰/채식 한식 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(반찬가게|반찬전문|밑반찬|김치전문|젓갈전문)', '한식당', '음식점', '반찬 전문점 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(돌솥밥|영양밥|솥밥|가마솥밥|돌솥정식)', '한식당', '음식점', '돌솥밥 전문점 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(막걸리|동동주|전통주|전통주점|민속주점)', '한식당', '음식점', '전통주점 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(도가니|도가니탕|꼬리탕|사골탕|진국)', '한식당', '음식점', '도가니/사골 전문점 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(육회|육사시미|한우육회|육회비빔밥|뭉티기)', '한식당', '음식점', '육회 전문점 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(곰국시|곰국|할매국밥|할매집|시골밥상)', '한식당', '음식점', '시골/전통 한식당 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(파리바게뜨|파리바게트|PARIS\s*BAGUETTE|PB|파바)', '베이커리', '음식점', '파리바게뜨 브랜드 패턴', 90, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.9}'::jsonb),
  ('(뚜레쥬르|뚜레주르|TOUS\s*LES\s*JOURS|뚜레)', '베이커리', '음식점', '뚜레쥬르 브랜드 패턴', 90, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.9}'::jsonb),
  ('(던킨도너츠|던킨|DUNKIN\s*DONUTS|DUNKIN|DD)', '베이커리', '음식점', '던킨도너츠 브랜드 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(크리스피크림|크리스피|KRISPY\s*KREME|KK|크크)', '베이커리', '음식점', '크리스피크림 브랜드 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(성심당|대전성심당|튀김소보로|부추빵)', '베이커리', '음식점', '성심당 브랜드 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(빵집|베이커리|BAKERY|제과점|제빵소)', '베이커리', '음식점', '베이커리 일반 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(브레드|BREAD|브래드|홈메이드|수제빵)', '베이커리', '음식점', '빵 전문점 일반 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(케이크|케익|CAKE|생일케이크|웨딩케이크)', '베이커리', '음식점', '케이크 전문점 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(도넛|도너츠|DONUT|DOUGHNUT|꽈배기)', '베이커리', '음식점', '도넛 전문점 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(크로와상|크루아상|CROISSANT|페이스트리|PASTRY)', '베이커리', '음식점', '프랑스 베이커리 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(바게트|바게뜨|BAGUETTE|프랑스빵|불란서빵)', '베이커리', '음식점', '프랑스빵 전문점 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(마카롱|마카롱전문|MACARON|프렌치마카롱)', '베이커리', '음식점', '마카롱 전문점 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(타르트|타르트전문|TART|에그타르트|과일타르트)', '베이커리', '음식점', '타르트 전문점 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(머핀|MUFFIN|컵케이크|CUPCAKE|미니케이크)', '베이커리', '음식점', '머핀/컵케이크 전문점 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(브라우니|BROWNIE|초콜릿케이크|초코케이크)', '베이커리', '음식점', '브라우니/초콜릿 전문점 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(티라미수|TIRAMISU|이탈리안디저트|젤라또)', '베이커리', '음식점', '이탈리안 디저트 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(치아바타|포카치아|FOCACCIA|이탈리안브레드)', '베이커리', '음식점', '이탈리안 베이커리 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(베이글|BAGEL|뉴욕베이글|크림치즈베이글)', '베이커리', '음식점', '베이글 전문점 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(프레첼|프레즐|PRETZEL|독일빵|호밀빵)', '베이커리', '음식점', '독일식 베이커리 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(스콘|SCONE|잉글리시머핀|브리티시베이커리)', '베이커리', '음식점', '영국식 베이커리 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(에클레어|ECLAIR|슈크림|크림빵|슈)', '베이커리', '음식점', '에클레어/슈 전문점 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(카스테라|카스텔라|CASTELLA|대만카스테라|촉촉한카스테라)', '베이커리', '음식점', '카스테라 전문점 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(소금빵|시오빵|버터롤|우유빵|크림빵)', '베이커리', '음식점', '일본식 베이커리 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(앙버터|앙금빵|팥빵|단팥빵|찐빵)', '베이커리', '음식점', '앙금빵 전문점 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(소보로|소보루|소보로빵|단팥소보로|땅콩소보로)', '베이커리', '음식점', '소보로빵 관련 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(멜론빵|메론빵|MELON\s*PAN|메론판)', '베이커리', '음식점', '멜론빵 관련 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(식빵|토스트|TOAST|식빵전문|생식빵)', '베이커리', '음식점', '식빵 전문점 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(크로플|크로와상와플|CROFFLE|와플)', '베이커리', '음식점', '크로플/와플 전문점 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(파이|PIE|애플파이|호두파이|피칸파이)', '베이커리', '음식점', '파이 전문점 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(쿠키|COOKIE|수제쿠키|마들렌|휘낭시에)', '베이커리', '음식점', '쿠키 전문점 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(치즈케이크|CHEESECAKE|뉴욕치즈케이크|바스크치즈케이크)', '베이커리', '음식점', '치즈케이크 전문점 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(롤케이크|ROLL\s*CAKE|스위스롤|생크림롤)', '베이커리', '음식점', '롤케이크 전문점 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(파운드케이크|POUND\s*CAKE|버터케이크|마드레느)', '베이커리', '음식점', '파운드케이크 전문점 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(샌드위치|SANDWICH|샌드|토스트샌드위치)', '베이커리', '음식점', '샌드위치 전문점 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(브런치베이커리|브런치카페|올데이브런치|BRUNCH)', '베이커리', '음식점', '브런치 베이커리 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(디저트|DESSERT|수제디저트|프리미엄디저트)', '베이커리', '음식점', '디저트 전문점 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(글루텐프리|무글루텐|비건베이커리|VEGAN)', '베이커리', '음식점', '건강/특수 베이커리 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(통밀빵|호밀빵|잡곡빵|건강빵|유기농빵)', '베이커리', '음식점', '건강빵 전문점 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(천연발효|사워도우|SOURDOUGH|르방|천연효모)', '베이커리', '음식점', '천연발효빵 전문점 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(공방|아틀리에|ATELIER|수제과자|쁘띠가또)', '베이커리', '음식점', '프리미엄 베이커리 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(델리|DELI|베이커리카페|카페베이커리)', '베이커리', '음식점', '델리/카페형 베이커리 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(모닝빵|아침빵|조식빵|모닝롤|브렉퍼스트)', '베이커리', '음식점', '아침식사 베이커리 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(붕어빵|팥붕어빵|슈크림붕어빵|미니붕어빵)', '베이커리', '음식점', '붕어빵 전문점 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(호떡|호빵|찐빵|왕만두|고로케)', '베이커리', '음식점', '길거리 베이커리 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(꽃빵|마늘빵|모카빵|야채빵|양파빵)', '베이커리', '음식점', '특수빵 전문점 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(피자빵|핫도그빵|소시지빵|햄치즈빵)', '베이커리', '음식점', '조리빵 전문점 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(만쥬|MANJU|도라야키|찹쌀떡|떡빵)', '베이커리', '음식점', '일본식 전통과자 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(에그타르트전문|포르투갈에그타르트|마카오에그타르트)', '베이커리', '음식점', '에그타르트 전문점 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(24시베이커리|새벽베이커리|심야베이커리|올나잇)', '베이커리', '음식점', '24시간 베이커리 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(파리바게뜨|파리바게트|PARIS\s*BAGUETTE|PB|파바)', '베이커리', '음식점', '파리바게뜨 브랜드 패턴', 90, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.9}'::jsonb),
  ('(뚜레쥬르|뚜레주르|TOUS\s*LES\s*JOURS|뚜레)', '베이커리', '음식점', '뚜레쥬르 브랜드 패턴', 90, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.9}'::jsonb),
  ('(던킨도너츠|던킨|DUNKIN\s*DONUTS|DUNKIN|DD)', '베이커리', '음식점', '던킨도너츠 브랜드 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(크리스피크림|크리스피|KRISPY\s*KREME|KK|크크)', '베이커리', '음식점', '크리스피크림 브랜드 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(성심당|대전성심당|튀김소보로|부추빵)', '베이커리', '음식점', '성심당 브랜드 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(이성당|군산이성당|야채빵|팥빵명가)', '베이커리', '음식점', '이성당 브랜드 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(삼송빵집|전주삼송빵집|PNB|풍년제과)', '베이커리', '음식점', '지역 명물 베이커리 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(태극당|서울태극당|몽블랑|나폴레옹)', '베이커리', '음식점', '태극당 브랜드 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(나폴레옹과자점|나폴레옹베이커리|황남빵|경주빵)', '베이커리', '음식점', '지역 특산 베이커리 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(안스베이커리|앤스베이커리|옵스|OPS|브레댄코)', '베이커리', '음식점', '프리미엄 베이커리 브랜드 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(빵집|베이커리|BAKERY|제과점|제빵소|빵가게)', '베이커리', '음식점', '베이커리 일반 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(동네빵집|마을빵집|우리동네빵집|로컬베이커리)', '베이커리', '음식점', '동네 베이커리 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(수제빵|홈메이드|홈베이킹|핸드메이드|아티산)', '베이커리', '음식점', '수제 베이커리 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(빵공장|대량생산빵|공장빵|양산빵집)', '베이커리', '음식점', '대량생산 베이커리 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(식빵전문|생식빵|고급식빵|프리미엄식빵|식빵맛집)', '베이커리', '음식점', '식빵 전문점 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(노가다빵|일용직빵|현장빵|공사장빵|막노동빵)', '베이커리', '음식점', '현장 노동자 베이커리 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(크로와상전문|크루아상|CROISSANT|버터크로와상)', '베이커리', '음식점', '크로와상 전문점 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(바게트전문|바게뜨|BAGUETTE|프랑스빵|불란서빵)', '베이커리', '음식점', '바게트 전문점 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(치아바타|포카치아|CIABATTA|FOCACCIA|이탈리안빵)', '베이커리', '음식점', '이탈리안 베이커리 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(베이글전문|BAGEL|뉴욕베이글|몬트리올베이글)', '베이커리', '음식점', '베이글 전문점 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(도넛전문|도너츠|DONUT|DOUGHNUT|올드패션도넛)', '베이커리', '음식점', '도넛 전문점 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(소금빵|시오빵|버터롤|밀크브레드|생크림빵)', '베이커리', '음식점', '일본식 빵 전문점 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(카스테라|카스텔라|CASTELLA|대만카스테라|촉촉이)', '베이커리', '음식점', '카스테라 전문점 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(소보로빵|소보루|단팥빵|크림빵|야채빵)', '베이커리', '음식점', '한국식 단팥빵 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(마늘빵|갈릭브레드|GARLIC\s*BREAD|양파빵|치즈빵)', '베이커리', '음식점', '조리빵 전문점 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(케이크전문|케익|CAKE|생일케이크|커스텀케이크)', '베이커리', '음식점', '케이크 전문점 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(티라미수|TIRAMISU|몽블랑|오페라케이크|무스케이크)', '베이커리', '음식점', '프리미엄 케이크 전문점 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(치즈케이크|CHEESECAKE|뉴욕치즈|바스크치즈케이크)', '베이커리', '음식점', '치즈케이크 전문점 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(롤케이크|ROLL\s*CAKE|스위스롤|젤리롤|크림롤)', '베이커리', '음식점', '롤케이크 전문점 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(타르트|TART|에그타르트|과일타르트|레몬타르트)', '베이커리', '음식점', '타르트 전문점 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(마카롱|MACARON|프렌치마카롱|뚱카롱|마카롱전문)', '베이커리', '음식점', '마카롱 전문점 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(쿠키전문|COOKIE|수제쿠키|버터쿠키|초코칩쿠키)', '베이커리', '음식점', '쿠키 전문점 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(마들렌|휘낭시에|까눌레|CANELE|프렌치페이스트리)', '베이커리', '음식점', '프랑스 과자 전문점 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(에클레어|ECLAIR|슈크림|프로피테롤|크림퍼프)', '베이커리', '음식점', '슈 전문점 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(크로플|크로와상와플|CROFFLE|크로넛|하이브리드)', '베이커리', '음식점', '하이브리드 베이커리 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(파이전문|PIE|애플파이|호두파이|페칸파이)', '베이커리', '음식점', '파이 전문점 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(샌드위치|SANDWICH|크로크무슈|파니니|PANINI)', '베이커리', '음식점', '샌드위치 전문점 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(브런치카페|브런치베이커리|올데이브런치|BRUNCH)', '베이커리', '음식점', '브런치 베이커리 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(천연발효빵|사워도우|SOURDOUGH|르방|천연효모)', '베이커리', '음식점', '천연발효 베이커리 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(글루텐프리|무글루텐|GLUTEN\s*FREE|알러지프리)', '베이커리', '음식점', '글루텐프리 베이커리 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(비건베이커리|VEGAN|채식빵|무유제품|식물성)', '베이커리', '음식점', '비건 베이커리 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(통밀빵|호밀빵|잡곡빵|현미빵|건강빵)', '베이커리', '음식점', '건강빵 전문점 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(붕어빵|팥붕어빵|슈크림붕어빵|미니붕어빵|잉어빵)', '베이커리', '음식점', '붕어빵 전문점 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(호떡|꿀호떡|씨앗호떡|찹쌀호떡|미니호떡)', '베이커리', '음식점', '호떡 전문점 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(찐빵|왕만두|호빵|고로케|군고구마)', '베이커리', '음식점', '길거리 간식 베이커리 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(와플|WAFFLE|벨기에와플|리에주와플|아메리칸와플)', '베이커리', '음식점', '와플 전문점 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(프레첼|프레즐|PRETZEL|독일빵|브레첸)', '베이커리', '음식점', '독일식 베이커리 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(딸기케이크|생크림케이크|초코케이크|레드벨벳)', '베이커리', '음식점', '생크림케이크 전문점 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(24시베이커리|새벽빵집|심야베이커리|올나잇베이커리)', '베이커리', '음식점', '24시간 베이커리 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(탐앤탐스|TOM\s*N\s*TOMS|탐탐|토망토망스|탐앤톰스)', '프랜차이즈카페', '카페', '탐앤탐스 브랜드 패턴', 90, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.9}'::jsonb),
  ('(폴바셋|PAUL\s*BASSETT|폴바셋커피|폴베이셋)', '프랜차이즈카페', '카페', '폴바셋 브랜드 패턴', 90, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.9}'::jsonb),
  ('(빽다방|백다방|PAIK''S\s*COFFEE|빽스커피|빽커피)', '프랜차이즈카페', '카페', '빽다방 브랜드 패턴', 90, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.9}'::jsonb),
  ('(커피빈|COFFEE\s*BEAN|더커피빈|커피빈앤티리프)', '프랜차이즈카페', '카페', '커피빈 브랜드 패턴', 85, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.85}'::jsonb),
  ('(할리스|HOLLYS|할리스커피|홀리스)', '프랜차이즈카페', '카페', '할리스 브랜드 패턴', 85, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.85}'::jsonb),
  ('(파스쿠찌|PASCUCCI|파스쿠치|카페파스쿠찌)', '프랜차이즈카페', '카페', '파스쿠찌 브랜드 패턴', 85, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.85}'::jsonb),
  ('(드롭탑|DROP\s*TOP|카페드롭탑|드롭탑커피)', '프랜차이즈카페', '카페', '드롭탑 브랜드 패턴', 80, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.8}'::jsonb),
  ('(커피베이|COFFEE\s*BAY|커피베이24|커베)', '프랜차이즈카페', '카페', '커피베이 브랜드 패턴', 80, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.8}'::jsonb),
  ('(요거프레소|YOGERPRESSO|요거프레쏘|요프)', '프랜차이즈카페', '카페', '요거프레소 브랜드 패턴', 80, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.8}'::jsonb),
  ('(커피명가|COFFEE\s*MYUNGGA|커피명가에스프레소)', '프랜차이즈카페', '카페', '커피명가 브랜드 패턴', 75, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.75}'::jsonb),
  ('(카페띠아모|CAFFE\s*TI\s*AMO|띠아모|티아모)', '프랜차이즈카페', '카페', '카페띠아모 브랜드 패턴', 80, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.8}'::jsonb),
  ('(달콤커피|DAL\.KOMM|달콤|달컴커피)', '프랜차이즈카페', '카페', '달콤커피 브랜드 패턴', 80, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.8}'::jsonb),
  ('(커피스미스|COFFEE\s*SMITH|커피스미쓰|스미스커피)', '프랜차이즈카페', '카페', '커피스미스 브랜드 패턴', 80, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.8}'::jsonb),
  ('(셀렉토커피|SELECTO|셀렉토|셀렉토커피숍)', '프랜차이즈카페', '카페', '셀렉토커피 브랜드 패턴', 75, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.75}'::jsonb),
  ('(커피나무|COFFEE\s*NAMU|커피나무로스터스)', '프랜차이즈카페', '카페', '커피나무 브랜드 패턴', 75, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.75}'::jsonb),
  ('(망고식스|MANGO\s*SIX|망고6|망식)', '프랜차이즈카페', '카페', '망고식스 브랜드 패턴', 80, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.8}'::jsonb),
  ('(카페드파리|CAFE\s*DE\s*PARIS|카드파|파리카페)', '프랜차이즈카페', '카페', '카페드파리 브랜드 패턴', 75, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.75}'::jsonb),
  ('(그라찌에|GRAZIE|그라찌에커피|그라제)', '프랜차이즈카페', '카페', '그라찌에 브랜드 패턴', 75, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.75}'::jsonb),
  ('(카페보니또|BONITO|보니또|보니토커피)', '프랜차이즈카페', '카페', '카페보니또 브랜드 패턴', 75, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.75}'::jsonb),
  ('(커피에반하다|반하다|에반하다|BANHADA)', '프랜차이즈카페', '카페', '커피에반하다 브랜드 패턴', 75, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.75}'::jsonb),
  ('(더착한커피|착한커피|THE착한|착커)', '프랜차이즈카페', '카페', '더착한커피 브랜드 패턴', 75, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.75}'::jsonb),
  ('(카페마마스|CAFE\s*MAMAS|마마스|카페마마)', '프랜차이즈카페', '카페', '카페마마스 브랜드 패턴', 75, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.75}'::jsonb),
  ('(하삼동커피|HASAMDONG|하삼동|삼동커피)', '프랜차이즈카페', '카페', '하삼동커피 브랜드 패턴', 80, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.8}'::jsonb),
  ('(카페봄봄|CAFE\s*BOMBOM|봄봄|봄봄커피)', '프랜차이즈카페', '카페', '카페봄봄 브랜드 패턴', 75, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.75}'::jsonb),
  ('(더리터|THE\s*LITER|더리터커피|리터커피)', '프랜차이즈카페', '카페', '더리터 브랜드 패턴', 75, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.75}'::jsonb),
  ('(매머드커피|MAMMOTH|매머드|맘모스커피)', '프랜차이즈카페', '카페', '매머드커피 브랜드 패턴', 80, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.8}'::jsonb),
  ('(커피온리|COFFEE\s*ONLY|커피온니|온리커피)', '프랜차이즈카페', '카페', '커피온리 브랜드 패턴', 75, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.75}'::jsonb),
  ('(감성커피|GAMSUNG|감성|감커)', '프랜차이즈카페', '카페', '감성커피 브랜드 패턴', 75, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.75}'::jsonb),
  ('(커피볶는집|볶는집|ROASTING\s*HOUSE|로스팅하우스)', '프랜차이즈카페', '카페', '커피볶는집 브랜드 패턴', 75, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.75}'::jsonb),
  ('(빈스빈스|BEANS\s*BINS|빈스빈즈|빈빈)', '프랜차이즈카페', '카페', '빈스빈스 브랜드 패턴', 75, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.75}'::jsonb),
  ('(카페아띠|CAFE\s*ATTI|아띠|아티커피)', '프랜차이즈카페', '카페', '카페아띠 브랜드 패턴', 70, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.7}'::jsonb),
  ('(토프레소|TOPRESSO|토프|탑프레소)', '프랜차이즈카페', '카페', '토프레소 브랜드 패턴', 70, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.7}'::jsonb),
  ('(카페세나|SENA|세나커피|카페쎄나)', '프랜차이즈카페', '카페', '카페세나 브랜드 패턴', 70, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.7}'::jsonb),
  ('(카페라떼아트|LATTE\s*ART|라떼아트|라떼아트커피)', '프랜차이즈카페', '카페', '카페라떼아트 브랜드 패턴', 70, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.7}'::jsonb),
  ('(드립앤드립|DRIP\s*&\s*DRIP|드립드립|드앤드)', '프랜차이즈카페', '카페', '드립앤드립 브랜드 패턴', 70, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.7}'::jsonb),
  ('(커피플레이스|COFFEE\s*PLACE|커플|플레이스커피)', '프랜차이즈카페', '카페', '커피플레이스 브랜드 패턴', 70, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.7}'::jsonb),
  ('(카페7그램|7GRAM|세븐그램|7그램커피)', '프랜차이즈카페', '카페', '카페7그램 브랜드 패턴', 70, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.7}'::jsonb),
  ('(카페노티드|NOTED|노티드|노티드커피)', '프랜차이즈카페', '카페', '카페노티드 브랜드 패턴', 75, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.75}'::jsonb),
  ('(커피팩토리|COFFEE\s*FACTORY|팩토리|팩토리커피)', '프랜차이즈카페', '카페', '커피팩토리 브랜드 패턴', 70, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.7}'::jsonb),
  ('(카페리브레|LIBRE|리브레|리브레커피)', '프랜차이즈카페', '카페', '카페리브레 브랜드 패턴', 70, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.7}'::jsonb),
  ('(모카블렌드|MOCA\s*BLEND|모카|블렌드커피)', '프랜차이즈카페', '카페', '모카블렌드 브랜드 패턴', 70, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.7}'::jsonb),
  ('(카페코지|COZY|코지|코지커피)', '프랜차이즈카페', '카페', '카페코지 브랜드 패턴', 70, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.7}'::jsonb),
  ('(커피타임|COFFEE\s*TIME|타임|타임커피)', '프랜차이즈카페', '카페', '커피타임 브랜드 패턴', 70, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.7}'::jsonb),
  ('(카페클라우드|CLOUD|클라우드|클라우드커피)', '프랜차이즈카페', '카페', '카페클라우드 브랜드 패턴', 70, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.7}'::jsonb),
  ('(카페포레|FORE|포레|포레커피)', '프랜차이즈카페', '카페', '카페포레 브랜드 패턴', 70, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.7}'::jsonb),
  ('(더센터커피|THE\s*CENTER|센터커피|더센터)', '프랜차이즈카페', '카페', '더센터커피 브랜드 패턴', 70, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.7}'::jsonb),
  ('(블루포트|BLUE\s*POT|블루팟|블포)', '프랜차이즈카페', '카페', '블루포트 브랜드 패턴', 70, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.7}'::jsonb),
  ('(카페베네치아|VENEZIA|베네치아|베네치아커피)', '프랜차이즈카페', '카페', '카페베네치아 브랜드 패턴', 70, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.7}'::jsonb),
  ('(카페인중독|CAFFEINE|인중독|카페인커피)', '프랜차이즈카페', '카페', '카페인중독 브랜드 패턴', 70, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.7}'::jsonb),
  ('(스타벅스|STARBUCKS|스벅|별다방|SBUX)', '커피전문점', '카페', '스타벅스 브랜드 패턴', 95, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.95}'::jsonb),
  ('(투썸플레이스|A\s*TWOSOME\s*PLACE|투썸|TWOSOME)', '커피전문점', '카페', '투썸플레이스 브랜드 패턴', 90, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.9}'::jsonb),
  ('(엔젤리너스|ANGEL\s*IN\s*US|엔제리너스|엔젤인어스)', '커피전문점', '카페', '엔젤리너스 브랜드 패턴', 90, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.9}'::jsonb),
  ('(카페베네|CAFFE\s*BENE|CAFFEBENE|베네)', '커피전문점', '카페', '카페베네 브랜드 패턴', 90, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.9}'::jsonb),
  ('(이디야|EDIYA|이디야커피|에디야)', '커피전문점', '카페', '이디야 브랜드 패턴', 90, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.9}'::jsonb),
  ('(메가커피|MEGA\s*COFFEE|메가MGC커피|메가)', '커피전문점', '카페', '메가커피 브랜드 패턴', 90, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.9}'::jsonb),
  ('(컴포즈커피|COMPOSE\s*COFFEE|컴포즈|COMPOSE)', '커피전문점', '카페', '컴포즈커피 브랜드 패턴', 90, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.9}'::jsonb),
  ('(커피빈앤티리프|COFFEE\s*BEAN\s*&\s*TEA\s*LEAF|CBTL)', '커피전문점', '카페', '커피빈앤티리프 풀네임 패턴', 85, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.85}'::jsonb),
  ('(더벤티|THE\s*VENTI|더벤티커피|벤티)', '커피전문점', '카페', '더벤티 브랜드 패턴', 85, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.85}'::jsonb),
  ('(블루보틀|BLUE\s*BOTTLE|블루보틀커피|블보)', '커피전문점', '카페', '블루보틀 브랜드 패턴', 85, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.85}'::jsonb),
  ('(테라로사|TERAROSA|테라로사커피|테라)', '커피전문점', '카페', '테라로사 브랜드 패턴', 85, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.85}'::jsonb),
  ('(커피리브레|COFFEE\s*LIBRE|리브레|커리브)', '커피전문점', '카페', '커피리브레 브랜드 패턴', 80, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.8}'::jsonb),
  ('(모모스커피|MOMOS|모모스|모모스테이블)', '커피전문점', '카페', '모모스커피 브랜드 패턴', 80, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.8}'::jsonb),
  ('(앤트러사이트|ANTHRACITE|앤트러|안트라사이트)', '커피전문점', '카페', '앤트러사이트 브랜드 패턴', 80, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.8}'::jsonb),
  ('(프릳츠|FRITZ|프릳츠커피|프리츠)', '커피전문점', '카페', '프릳츠 브랜드 패턴', 80, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.8}'::jsonb),
  ('(커피몽타주|COFFEE\s*MONTAGE|몽타주|몽타주커피)', '커피전문점', '카페', '커피몽타주 브랜드 패턴', 75, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.75}'::jsonb),
  ('(카페꼼마|CAFE\s*COMMA|꼼마|콤마커피)', '커피전문점', '카페', '카페꼼마 브랜드 패턴', 75, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.75}'::jsonb),
  ('(헬카페|HELL\s*CAFE|헬커피|HELL\s*COFFEE)', '커피전문점', '카페', '헬카페 브랜드 패턴', 75, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.75}'::jsonb),
  ('(스페셜티커피|SPECIALTY|스페셜티|로스터리)', '커피전문점', '카페', '스페셜티 커피전문점 일반 패턴', 80, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.8}'::jsonb),
  ('(핸드드립|HAND\s*DRIP|드립커피|브루잉)', '커피전문점', '카페', '핸드드립 전문점 패턴', 75, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.75}'::jsonb),
  ('(로스터리카페|ROASTERY|로스팅|커피로스터리)', '커피전문점', '카페', '로스터리 카페 패턴', 80, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.8}'::jsonb),
  ('(에스프레소바|ESPRESSO\s*BAR|에스프레소전문|바리스타)', '커피전문점', '카페', '에스프레소바 패턴', 75, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.75}'::jsonb),
  ('(콜드브루|COLD\s*BREW|더치커피|DUTCH\s*COFFEE)', '커피전문점', '카페', '콜드브루 전문점 패턴', 75, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.75}'::jsonb),
  ('(커피공방|COFFEE\s*WORKSHOP|커피작업실|커피아뜰리에)', '커피전문점', '카페', '커피공방 패턴', 75, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.75}'::jsonb),
  ('(커피전문점|커피숍|COFFEE\s*SHOP|카페|CAFE)', '커피전문점', '카페', '커피전문점 일반 패턴', 70, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.7}'::jsonb),
  ('(24시커피|24시간커피|무인카페|무인커피)', '커피전문점', '카페', '24시/무인 커피전문점 패턴', 75, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.75}'::jsonb),
  ('(커피하우스|COFFEE\s*HOUSE|커피홀|커피라운지)', '커피전문점', '카페', '커피하우스 패턴', 70, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.7}'::jsonb),
  ('(디저트카페|DESSERT\s*CAFE|케이크카페|브런치카페)', '커피전문점', '카페', '디저트/브런치 카페 패턴', 75, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.75}'::jsonb),
  ('(북카페|BOOK\s*CAFE|스터디카페|공부카페)', '커피전문점', '카페', '북카페/스터디카페 패턴', 70, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.7}'::jsonb),
  ('(루프탑카페|ROOFTOP|옥상카페|테라스카페)', '커피전문점', '카페', '루프탑/테라스 카페 패턴', 70, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.7}'::jsonb),
  ('(펫카페|PET\s*CAFE|애견카페|강아지카페|고양이카페)', '커피전문점', '카페', '펫카페 패턴', 70, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.7}'::jsonb),
  ('(드라이브스루|DRIVE\s*THRU|DT점|차안에서)', '커피전문점', '카페', '드라이브스루 전문점 패턴', 75, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.75}'::jsonb),
  ('(커피앤베이커리|COFFEE\s*&\s*BAKERY|카페베이커리)', '커피전문점', '카페', '커피&베이커리 복합점 패턴', 75, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.75}'::jsonb),
  ('(아메리카노전문|라떼전문|카푸치노|플랫화이트)', '커피전문점', '카페', '특정 메뉴 전문점 패턴', 70, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.7}'::jsonb),
  ('(테이크아웃전문|TAKEOUT|TO\s*GO|포장전문)', '커피전문점', '카페', '테이크아웃 전문점 패턴', 70, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.7}'::jsonb),
  ('(커피트럭|COFFEE\s*TRUCK|이동카페|푸드트럭)', '커피전문점', '카페', '커피트럭 패턴', 70, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.7}'::jsonb),
  ('(프리미엄커피|PREMIUM|고급커피|수입커피)', '커피전문점', '카페', '프리미엄 커피전문점 패턴', 75, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.75}'::jsonb),
  ('(싱글오리진|SINGLE\s*ORIGIN|원두전문|생두)', '커피전문점', '카페', '싱글오리진 전문점 패턴', 70, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.7}'::jsonb),
  ('(아라비카|ARABICA|로부스타|ROBUSTA|커피품종)', '커피전문점', '카페', '커피품종 전문점 패턴', 70, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.7}'::jsonb),
  ('(큐그레이더|Q\s*GRADER|커피감정사|바리스타인증)', '커피전문점', '카페', '전문가 운영 커피전문점 패턴', 70, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.7}'::jsonb),
  ('(라떼아트|LATTE\s*ART|로제타|하트|튤립)', '커피전문점', '카페', '라떼아트 전문점 패턴', 70, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.7}'::jsonb),
  ('(사이폰커피|SIPHON|모카포트|MOKA\s*POT|케멕스)', '커피전문점', '카페', '특수추출 커피전문점 패턴', 70, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.7}'::jsonb),
  ('(브루어리카페|BREWERY|맥주카페|커피맥주)', '커피전문점', '카페', '브루어리 카페 패턴', 70, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.7}'::jsonb),
  ('(코워킹카페|CO\s*WORKING|업무카페|비즈니스카페)', '커피전문점', '카페', '코워킹 카페 패턴', 70, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.7}'::jsonb),
  ('(시그니처커피|SIGNATURE|시그니처메뉴|대표메뉴)', '커피전문점', '카페', '시그니처 메뉴 전문점 패턴', 70, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.7}'::jsonb),
  ('(친환경카페|ECO\s*CAFE|제로웨이스트|텀블러)', '커피전문점', '카페', '친환경 카페 패턴', 70, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.7}'::jsonb),
  ('(스마트오더|SMART\s*ORDER|앱주문|키오스크)', '커피전문점', '카페', '스마트오더 전문점 패턴', 70, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.7}'::jsonb),
  ('(구독커피|SUBSCRIPTION|정기배송|커피구독)', '커피전문점', '카페', '구독형 커피전문점 패턴', 70, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.7}'::jsonb),
  ('(갤러리카페|GALLERY\s*CAFE|전시카페|아트카페)', '커피전문점', '카페', '갤러리 카페 패턴', 70, '{"source": "json_conversion", "original_category": "카페", "confidence": 0.7}'::jsonb),
  ('(BBQ|비비큐|BBQ치킨|BBQ올리브치킨|비비큐치킨)', '치킨전문점', '음식점', 'BBQ 브랜드 패턴', 95, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.95}'::jsonb),
  ('(교촌치킨|KYOCHON|교촌|교촌에프앤비|KyoChon)', '치킨전문점', '음식점', '교촌치킨 브랜드 패턴', 95, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.95}'::jsonb),
  ('(BHC|BHC치킨|비에이치씨|뿌링클|맛초킹)', '치킨전문점', '음식점', 'BHC 브랜드 패턴', 90, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.9}'::jsonb),
  ('(네네치킨|NENE|네네|NeNe|네네치킨파닭)', '치킨전문점', '음식점', '네네치킨 브랜드 패턴', 90, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.9}'::jsonb),
  ('(굽네치킨|GOOBNE|굽네|굽네갈비천왕|고추바사삭)', '치킨전문점', '음식점', '굽네치킨 브랜드 패턴', 90, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.9}'::jsonb),
  ('(푸라닭|PURADAK|푸라닭치킨|블랙알리오)', '치킨전문점', '음식점', '푸라닭 브랜드 패턴', 90, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.9}'::jsonb),
  ('(페리카나|PELICANA|페리카나치킨|양념통닭)', '치킨전문점', '음식점', '페리카나 브랜드 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(호식이두마리치킨|호식이|두마리치킨|호치킨)', '치킨전문점', '음식점', '호식이두마리치킨 브랜드 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(멕시카나|MEXICANA|멕시카나치킨|땡초치킨)', '치킨전문점', '음식점', '멕시카나 브랜드 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(또래오래|또래오래치킨|또오치|신호등치킨)', '치킨전문점', '음식점', '또래오래 브랜드 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(처갓집양념치킨|처갓집|처갓집슈프림|슈프림양념)', '치킨전문점', '음식점', '처갓집양념치킨 브랜드 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(맘스터치|MOM''S\s*TOUCH|맘터|싸이버거세트)', '치킨전문점', '음식점', '맘스터치 브랜드 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(60계치킨|육공계|60계|60계스파이시)', '치킨전문점', '음식점', '60계치킨 브랜드 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(치킨플러스|CHICKEN\s*PLUS|치플|깐풍치킨)', '치킨전문점', '음식점', '치킨플러스 브랜드 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(자담치킨|JADAM|자담|숯불치킨)', '치킨전문점', '음식점', '자담치킨 브랜드 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(노랑통닭|노랑|노랑치킨|압구정노랑통닭)', '치킨전문점', '음식점', '노랑통닭 브랜드 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(티바두마리치킨|티바|TIBA|두마리)', '치킨전문점', '음식점', '티바두마리치킨 브랜드 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(후라이드참잘하는집|후참|참잘|후라이드전문)', '치킨전문점', '음식점', '후라이드참잘하는집 브랜드 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(치킨매니아|CHICKEN\s*MANIA|치매|매니아)', '치킨전문점', '음식점', '치킨매니아 브랜드 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(신통치킨|신통|통닭|옛날통닭)', '치킨전문점', '음식점', '신통치킨 브랜드 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(부어치킨|BOOR|부어|맥주치킨)', '치킨전문점', '음식점', '부어치킨 브랜드 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(가마로강정|가마로|강정치킨|간장강정)', '치킨전문점', '음식점', '가마로강정 브랜드 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(피자나라치킨공주|피자나라|치킨공주|피치공)', '치킨전문점', '음식점', '피자나라치킨공주 브랜드 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(돈치킨|DON|돈까스치킨|치킨까스)', '치킨전문점', '음식점', '돈치킨 브랜드 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(오븐마루|OVEN\s*MARU|오븐마루치킨|오븐구이)', '치킨전문점', '음식점', '오븐마루 브랜드 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(구구치킨|99|구구|숯불바베큐)', '치킨전문점', '음식점', '구구치킨 브랜드 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(치킨|CHICKEN|통닭|닭튀김|프라이드치킨)', '치킨전문점', '음식점', '치킨 일반 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(후라이드|프라이드|FRIED|후치|크리스피)', '치킨전문점', '음식점', '후라이드치킨 일반 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(양념치킨|양념통닭|간장치킨|매운치킨|순한치킨)', '치킨전문점', '음식점', '양념치킨 일반 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(파닭|파치킨|대파치킨|파닭치킨)', '치킨전문점', '음식점', '파닭 관련 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(닭강정|강정|순살강정|매운강정|간장강정)', '치킨전문점', '음식점', '닭강정 관련 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(순살치킨|순살|뼈없는치킨|순살텐더)', '치킨전문점', '음식점', '순살치킨 관련 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(전기구이치킨|전기구이통닭|로티세리|구이치킨)', '치킨전문점', '음식점', '전기구이치킨 관련 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(숯불치킨|숯불구이|바베큐치킨|BBQ구이)', '치킨전문점', '음식점', '숯불치킨 관련 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(오븐치킨|오븐구이|베이크치킨|구운치킨)', '치킨전문점', '음식점', '오븐치킨 관련 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(반반치킨|반반|하프앤하프|믹스치킨)', '치킨전문점', '음식점', '반반치킨 관련 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(치킨너겟|너겟|텐더|치킨텐더|닭가슴살)', '치킨전문점', '음식점', '치킨너겟/텐더 관련 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(윙|봉|날개|닭날개|윙봉)', '치킨전문점', '음식점', '윙/봉 관련 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(24시치킨|새벽치킨|심야치킨|올나잇치킨)', '치킨전문점', '음식점', '24시 치킨 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(치킨배달|배달치킨|치킨딜리버리|퀵치킨)', '치킨전문점', '음식점', '치킨배달 관련 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(치맥|치킨맥주|호프치킨|비어치킨)', '치킨전문점', '음식점', '치맥 관련 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(옛날치킨|전통치킨|시장치킨|재래식치킨)', '치킨전문점', '음식점', '옛날치킨 관련 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(신선치킨|생치킨|당일치킨|냉동안함)', '치킨전문점', '음식점', '신선치킨 관련 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(프리미엄치킨|수제치킨|장인치킨|명품치킨)', '치킨전문점', '음식점', '프리미엄치킨 관련 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(1인치킨|혼술치킨|혼밥치킨|소량치킨)', '치킨전문점', '음식점', '1인 치킨 관련 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(치킨버거|치킨샌드위치|치킨랩|치킨또띠아)', '치킨전문점', '음식점', '치킨버거 관련 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(치킨무|무|치킨소스|양념소스|딥소스)', '치킨전문점', '음식점', '치킨 부가메뉴 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(치킨세트|세트메뉴|콜라세트|맥주세트)', '치킨전문점', '음식점', '치킨세트 관련 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(치킨테이크아웃|포장치킨|TO\s*GO|픽업치킨)', '치킨전문점', '음식점', '테이크아웃 치킨 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(아웃백|OUTBACK|아웃백스테이크하우스|OUTBACK\s*STEAKHOUSE)', '양식당', '음식점', '아웃백 브랜드 패턴', 90, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.9}'::jsonb),
  ('(티지아이프라이데이|TGIF|TGI\s*FRIDAY''S|티지아이)', '양식당', '음식점', 'TGIF 브랜드 패턴', 90, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.9}'::jsonb),
  ('(빕스|VIPS|빕스프리미어|VIPS\s*PREMIER)', '양식당', '음식점', '빕스 브랜드 패턴', 90, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.9}'::jsonb),
  ('(애슐리|ASHLEY|애슐리퀸즈|애슐리W)', '양식당', '음식점', '애슐리 브랜드 패턴', 90, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.9}'::jsonb),
  ('(토니로마스|TONY\s*ROMA''S|토니|토로마)', '양식당', '음식점', '토니로마스 브랜드 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(매드포갈릭|MAD\s*FOR\s*GARLIC|매드갈릭|매포갈)', '양식당', '음식점', '매드포갈릭 브랜드 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(온더보더|ON\s*THE\s*BORDER|온더보더멕시칸)', '양식당', '음식점', '온더보더 브랜드 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(베니건스|BENNIGAN''S|베니건|베니건스그릴)', '양식당', '음식점', '베니건스 브랜드 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(스테이크|STEAK|스테이크하우스|STEAKHOUSE)', '양식당', '음식점', '스테이크 전문점 일반 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(티본|T-BONE|티본스테이크|립아이|RIB\s*EYE)', '양식당', '음식점', '스테이크 부위별 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(안심|등심|채끝|꽃등심|부채살)', '양식당', '음식점', '한국식 스테이크 부위 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(파스타|PASTA|스파게티|SPAGHETTI|페투치니|FETTUCCINE)', '양식당', '음식점', '파스타 일반 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(까르보나라|CARBONARA|알리오올리오|AGLIO\s*OLIO)', '양식당', '음식점', '파스타 종류별 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(로제파스타|크림파스타|토마토파스타|오일파스타)', '양식당', '음식점', '파스타 소스별 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(봉골레|VONGOLE|아라비아타|ARRABBIATA|푸타네스카)', '양식당', '음식점', '이탈리안 파스타 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(리조또|RISOTTO|리조토|필라프|PILAF)', '양식당', '음식점', '리조또/필라프 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(그라탕|GRATIN|라자냐|LASAGNA|뇨끼|GNOCCHI)', '양식당', '음식점', '오븐 요리 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(이탈리안|ITALIAN|이태리|이탈리아)', '양식당', '음식점', '이탈리안 레스토랑 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(프렌치|FRENCH|프랑스요리|불란서요리)', '양식당', '음식점', '프렌치 레스토랑 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(브런치|BRUNCH|브런치카페|올데이브런치)', '양식당', '음식점', '브런치 레스토랑 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(에그베네딕트|팬케이크|PANCAKE|프렌치토스트)', '양식당', '음식점', '브런치 메뉴 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(오믈렛|OMELET|스크램블|에그스크램블)', '양식당', '음식점', '계란 요리 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(피자|PIZZA|화덕피자|씬피자|시카고피자)', '양식당', '음식점', '피자 전문점 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(샐러드바|SALAD\s*BAR|셀러드바|뷔페)', '양식당', '음식점', '샐러드바 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(시저샐러드|CAESAR|코브샐러드|그릭샐러드)', '양식당', '음식점', '샐러드 종류별 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(수프|SOUP|스프|양송이수프|호박수프)', '양식당', '음식점', '수프 관련 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(클램차우더|민네스트로네|비스크|콘소메)', '양식당', '음식점', '수프 종류별 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(돈까스|DONKATSU|일본식돈까스|경양식)', '양식당', '음식점', '경양식 돈까스 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(함박스테이크|HAMBURG\s*STEAK|햄버그스테이크)', '양식당', '음식점', '함박스테이크 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(오므라이스|OMURICE|오무라이스|볶음밥오믈렛)', '양식당', '음식점', '오므라이스 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(포크커틀릿|PORK\s*CUTLET|치킨커틀릿|코르동블루)', '양식당', '음식점', '커틀릿 관련 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(그릴|GRILL|바베큐|BBQ|숯불구이)', '양식당', '음식점', '그릴 요리 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(립|RIBS|폭립|바비큐립|베이비백립)', '양식당', '음식점', '립 요리 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(치킨|로티세리치킨|그릴드치킨|허브치킨)', '양식당', '음식점', '양식 치킨 요리 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(해산물|SEAFOOD|씨푸드|랍스터|LOBSTER)', '양식당', '음식점', '해산물 요리 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(새우|쉬림프|SHRIMP|감바스|GAMBAS)', '양식당', '음식점', '새우 요리 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(연어|SALMON|연어스테이크|그릴드연어)', '양식당', '음식점', '연어 요리 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(와인|WINE|와인바|WINE\s*BAR|와인레스토랑)', '양식당', '음식점', '와인바/레스토랑 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(타파스|TAPAS|스페인요리|스패니시)', '양식당', '음식점', '스페인 요리 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(멕시칸|MEXICAN|타코|부리또|퀘사디아)', '양식당', '음식점', '멕시칸 요리 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(파인다이닝|FINE\s*DINING|고급양식|코스요리)', '양식당', '음식점', '파인다이닝 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(비스트로|BISTRO|캐주얼다이닝|브라스리)', '양식당', '음식점', '비스트로/캐주얼 다이닝 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(뷔페|BUFFET|부페|양식뷔페|씨푸드뷔페)', '양식당', '음식점', '양식 뷔페 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(런치세트|LUNCH\s*SET|런치코스|비즈니스런치)', '양식당', '음식점', '런치세트 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(디너코스|DINNER\s*COURSE|정찬|풀코스)', '양식당', '음식점', '디너코스 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(애피타이저|APPETIZER|전채요리|스타터)', '양식당', '음식점', '전채요리 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(디저트|DESSERT|티라미수|판나코타|크렘브륄레)', '양식당', '음식점', '양식 디저트 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(바|BAR|펍|PUB|가스트로펍|GASTROPUB)', '양식당', '음식점', '바/펍 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(양식|서양요리|웨스턴|WESTERN|유럽요리)', '양식당', '음식점', '양식 일반 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(김밥천국|김천|KIMBAB\s*HEAVEN|김밥천국분식)', '분식점', '음식점', '김밥천국 브랜드 패턴', 90, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.9}'::jsonb),
  ('(김밥나라|김밥나루|KIMBAB\s*NARA|김나)', '분식점', '음식점', '김밥나라 브랜드 패턴', 90, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.9}'::jsonb),
  ('(신전떡볶이|신전|SINJEON|신전떡볶이본점)', '분식점', '음식점', '신전떡볶이 브랜드 패턴', 90, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.9}'::jsonb),
  ('(엽기떡볶이|엽떡|YUPDDUK|엽기)', '분식점', '음식점', '엽기떡볶이 브랜드 패턴', 90, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.9}'::jsonb),
  ('(죠스떡볶이|죠스|JAWS|죠떡)', '분식점', '음식점', '죠스떡볶이 브랜드 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(떡참|떡참떡볶이|DDUK\s*CHAM|떡참본점)', '분식점', '음식점', '떡참 브랜드 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(국대떡볶이|국대|국떡|GUKDAE)', '분식점', '음식점', '국대떡볶이 브랜드 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(아딸|아딸떡볶이|ADDAL|아딸본점)', '분식점', '음식점', '아딸 브랜드 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(김밥|KIMBAB|GIMBAP|김밥집|김밥전문)', '분식점', '음식점', '김밥 일반 패턴', 90, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.9}'::jsonb),
  ('(참치김밥|야채김밥|충무김밥|누드김밥|꼬마김밥)', '분식점', '음식점', '김밥 종류별 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(떡볶이|떡볶기|떡뽀끼|TTEOKBOKKI|DDUKBOKKI)', '분식점', '음식점', '떡볶이 일반 패턴', 90, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.9}'::jsonb),
  ('(로제떡볶이|짜장떡볶이|궁중떡볶이|국물떡볶이)', '분식점', '음식점', '떡볶이 종류별 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(라면|라멘|RAMEN|RAMYEON|컵라면)', '분식점', '음식점', '라면 관련 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(신라면|진라면|너구리|안성탕면|짜파게티)', '분식점', '음식점', '라면 브랜드별 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(라볶이|라볶기|라면떡볶이|짜파구리|짜파게티라면)', '분식점', '음식점', '라면 응용 메뉴 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(튀김|TWIGIM|야채튀김|오징어튀김|고구마튀김)', '분식점', '음식점', '튀김 관련 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(김말이|춘권|깻잎튀김|새우튀김|만두튀김)', '분식점', '음식점', '튀김 종류별 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(순대|SUNDAE|순댓국|찰순대|당면순대)', '분식점', '음식점', '순대 관련 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(순대볶음|순대꼬치|순대정식|모듬순대)', '분식점', '음식점', '순대 메뉴 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(어묵|오뎅|EOMUK|ODEN|어묵탕)', '분식점', '음식점', '어묵 관련 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(꼬치어묵|어묵국물|어묵바|매운어묵)', '분식점', '음식점', '어묵 종류별 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(만두|MANDU|군만두|물만두|찐만두)', '분식점', '음식점', '만두 관련 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(왕만두|고기만두|김치만두|야채만두|새우만두)', '분식점', '음식점', '만두 종류별 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(쫄면|쫄면무침|비빔쫄면|매운쫄면)', '분식점', '음식점', '쫄면 관련 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(국수|잔치국수|비빔국수|멸치국수|소면)', '분식점', '음식점', '국수 관련 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(우동|UDON|가락우동|어묵우동|김치우동)', '분식점', '음식점', '우동 관련 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(비빔밥|돌솥비빔밥|야채비빔밥|참치비빔밥)', '분식점', '음식점', '분식점 비빔밥 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(볶음밥|김치볶음밥|새우볶음밥|햄볶음밥)', '분식점', '음식점', '볶음밥 관련 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(덮밥|제육덮밥|오징어덮밥|참치덮밥)', '분식점', '음식점', '덮밥 관련 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(주먹밥|삼각김밥|충무김밥세트|김밥정식)', '분식점', '음식점', '주먹밥/세트 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(분식|분식집|분식점|BUNSIK|한식분식)', '분식점', '음식점', '분식점 일반 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(즉석떡볶이|즉떡|컵떡볶이|포장떡볶이)', '분식점', '음식점', '즉석떡볶이 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(떡강정|떡꼬치|떡튀김|매운떡강정)', '분식점', '음식점', '떡 응용메뉴 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(핫도그|소세지|햄치즈스틱|모짜핫도그)', '분식점', '음식점', '핫도그 관련 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(토스트|햄치즈토스트|계란토스트|야채토스트)', '분식점', '음식점', '토스트 관련 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(떡라면|떡만둣국|라면김밥|라면정식)', '분식점', '음식점', '라면 세트메뉴 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(분식세트|떡튀순|라볶이세트|김떡순)', '분식점', '음식점', '분식 세트메뉴 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(학교앞분식|학교분식|대학분식|캠퍼스분식)', '분식점', '음식점', '학교 분식점 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(시장분식|재래시장분식|전통시장분식)', '분식점', '음식점', '시장 분식점 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(24시분식|24시간분식|새벽분식|심야분식)', '분식점', '음식점', '24시간 분식점 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(포장마차|노점|길거리분식|트럭분식)', '분식점', '음식점', '포장마차/노점 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(떡볶이뷔페|분식뷔페|무한리필떡볶이)', '분식점', '음식점', '분식 뷔페 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(매운맛|중간맛|순한맛|신라면맛|짜장맛)', '분식점', '음식점', '맵기/맛 단계 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(치즈떡볶이|치즈김밥|치즈라면|치즈추가)', '분식점', '음식점', '치즈 토핑 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(계란추가|햄추가|김치추가|토핑추가)', '분식점', '음식점', '토핑 추가 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(단무지|깍두기|김치|반찬|무료반찬)', '분식점', '음식점', '분식점 반찬 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(분식체인|분식프랜차이즈|가맹점분식)', '분식점', '음식점', '분식 체인점 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(혼밥분식|1인분식|소량분식|미니세트)', '분식점', '음식점', '1인 분식 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(배달분식|분식배달|떡볶이배달|포장분식)', '분식점', '음식점', '분식 배달/포장 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(중식|중국집|중화요리|중국요리|중국음식|차이나푸드)', '중식당', '음식점', '중식당 일반 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(짜장면|자장면|짜장|자장|炸醬麵|JJAJANGMYEON)', '중식당', '음식점', '짜장면 관련 패턴', 90, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.9}'::jsonb),
  ('(짬뽕|챰뽕|짬봉|짬뽕밥|JJAMPPONG|炒碼麵)', '중식당', '음식점', '짬뽕 관련 패턴', 90, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.9}'::jsonb),
  ('(탕수육|탕슉|糖醋肉|TANGSUYUK|꿔바로우|锅包肉)', '중식당', '음식점', '탕수육 관련 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(마라탕|麻辣燙|MALATANG|마라샹궈|마라훠궈)', '중식당', '음식점', '마라탕/마라 요리 패턴', 90, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.9}'::jsonb),
  ('(탕화쿵푸|미스터짬뽕|홍콩반점|북경|베이징)', '중식당', '음식점', '중식 프랜차이즈 브랜드 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(진짜루|백짬뽕|역전우동0410중화|만리성|대만왕)', '중식당', '음식점', '국내 중식 체인점 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(간짜장|쟁반짜장|유니짜장|삼선짜장|사천짜장)', '중식당', '음식점', '짜장면 종류별 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(백짬뽕|삼선짬뽕|차돌짬뽕|해물짬뽕|고추짬뽕)', '중식당', '음식점', '짬뽕 종류별 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(볶음밥|炒飯|FRIEDRICE|새우볶음밥|짬뽕밥|짜장밥)', '중식당', '음식점', '볶음밥 관련 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(군만두|물만두|찐만두|교자|딤섬|点心)', '중식당', '음식점', '만두/딤섬 관련 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(춘권|春卷|스프링롤|SPRINGROLL|하르방)', '중식당', '음식점', '춘권 관련 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(훠궈|火鍋|HOTPOT|샤브샤브|중국식전골)', '중식당', '음식점', '훠궈/중국 전골 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(하이디라오|海底撈|HAIDILAO|샤오룽칸|小龙坎)', '중식당', '음식점', '훠궈 전문 브랜드 패턴', 90, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.9}'::jsonb),
  ('(양꼬치|양고기|羊肉串|양갈비|연태|칭다오)', '중식당', '음식점', '양꼬치/양고기 전문점 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(마파두부|麻婆豆腐|MAPOTOFU|사천요리|四川)', '중식당', '음식점', '사천요리 관련 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(깐풍기|깐풍육|乾烹|간풍|깐풍새우)', '중식당', '음식점', '깐풍 요리 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(팔보채|八宝菜|잡채밥|중화잡채|해물잡채)', '중식당', '음식점', '팔보채/잡채 관련 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(유산슬|油三絲|중화냉채|겨자냉채|냉채)', '중식당', '음식점', '중화 냉채 요리 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(난자완스|南煎丸子|동파육|東坡肉|중국식미트볼)', '중식당', '음식점', '중국 육류 요리 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(샤오마이|소룡포|小籠包|XIAOLONGBAO|만두전문)', '중식당', '음식점', '소룡포/만두 전문점 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(딘타이펑|鼎泰豊|DINTAIFUNG|남상창|南翔)', '중식당', '음식점', '딤섬 전문 브랜드 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(북경오리|베이징덕|北京烤鴨|PEKINGDUCK|오리구이)', '중식당', '음식점', '북경오리 전문점 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(크리스피덕|취영루|全聚德|쥐안쥐더)', '중식당', '음식점', '북경오리 브랜드 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(중식뷔페|중국뷔페|중화뷔페|무한리필중식)', '중식당', '음식점', '중식 뷔페 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(칠리새우|깐쇼새우|중화새우|왕새우요리)', '중식당', '음식점', '새우 요리 전문 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(멘보샤|面包虾|토스트새우|새우토스트)', '중식당', '음식점', '멘보샤 관련 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(라조기|라조육|辣椒|고추잡채|사천식고추)', '중식당', '음식점', '라조 요리 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(중국냉면|중화냉면|비빔냉면|사천냉면)', '중식당', '음식점', '중국식 냉면 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(울면|기스면|간짜면|짜장라면|중화라면)', '중식당', '음식점', '특수 면요리 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(동북|둥베이|東北|연변|조선족)', '중식당', '음식점', '동북/연변 요리 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(꿔티에|鍋貼|군만두|구운만두|팬프라이만두)', '중식당', '음식점', '꿔티에/구운만두 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(가지튀김|어향가지|魚香茄子|중화가지)', '중식당', '음식점', '가지 요리 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(중국식볶음|웍|WOK|불맛|화구)', '중식당', '음식점', '중식 볶음 요리 일반 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(월병|月餅|중국과자|중국떡|중화디저트)', '중식당', '음식점', '중국 디저트 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(중국차|중차|茶|우롱차|보이차|철관음)', '중식당', '음식점', '중국차 전문점 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(광동요리|広東|광둥|딤섬전문|얌차)', '중식당', '음식점', '광동요리 전문점 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(상해요리|上海|샹하이|상하이|강남요리)', '중식당', '음식점', '상해요리 전문점 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(산동요리|山東|산둥|교동반점|만물상)', '중식당', '음식점', '산동요리 전문점 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(쿵파오치킨|宮保鶏丁|궁보계정|땅콩닭)', '중식당', '음식점', '쿵파오치킨 관련 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(중국술|백주|白酒|마오타이|연태고량주)', '중식당', '음식점', '중국술 전문점 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(중화비빔밥|중국덮밥|마파덮밥|짜사이덮밥)', '중식당', '음식점', '중국식 덮밥 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(탄탄면|担担麺|DANDAN|중국비빔면|사천비빔면)', '중식당', '음식점', '탄탄면 관련 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(전가복|全家福|중화모듬|스페셜요리|중화특선)', '중식당', '음식점', '중화 특선요리 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(게살스프|계란탕|중국스프|상어지느러미)', '중식당', '음식점', '중국식 스프 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(중화오믈렛|계란요리|중국식계란|푸용하이)', '중식당', '음식점', '중국식 계란요리 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(중국가정식|중화가정식|집밥중식|중국엄마)', '중식당', '음식점', '중국 가정식 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(우육면|牛肉麺|중국우육면|란저우라면)', '중식당', '음식점', '우육면 전문점 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(중화포차|중국포차|마라포차|중국야시장)', '중식당', '음식점', '중국식 포차/야시장 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(스시|초밥|회전초밥|SUSHI|すし|寿司)', '일식당', '음식점', '스시/초밥 일반 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(스시로|스시잔마이|스시노미도리|스시효|스시쿠이네)', '일식당', '음식점', '스시 전문 브랜드 패턴', 90, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.9}'::jsonb),
  ('(갓덴스시|상무초밥|초밥천국|스시웨이|스시박스)', '일식당', '음식점', '국내 스시 프랜차이즈 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(오마카세|おまかせ|OMAKASE|셰프스초이스)', '일식당', '음식점', '오마카세 전문점 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(사시미|さしみ|刺身|생선회|활어회)', '일식당', '음식점', '사시미/회 전문점 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(라멘|라면|ラーメン|拉麺|RAMEN)', '일식당', '음식점', '라멘 일반 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(이치란|잇푸도|멘야산다이메|킷카타|하카타분코)', '일식당', '음식점', '라멘 전문 브랜드 패턴', 90, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.9}'::jsonb),
  ('(돈코츠|돈코쓰|豚骨|미소|된장|시오|소금|쇼유|간장)', '일식당', '음식점', '라멘 종류별 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(츠케멘|つけ麺|마제소바|아부라소바|탄탄멘)', '일식당', '음식점', '특수 라멘 종류 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(우동|うどん|UDON|사누키우동|가케우동)', '일식당', '음식점', '우동 전문점 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(마루가메제면|니쿠우동|역전우동|우동신|우동마루)', '일식당', '음식점', '우동 프랜차이즈 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(소바|そば|蕎麦|SOBA|메밀국수|자루소바)', '일식당', '음식점', '소바 전문점 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(돈까스|돈카츠|とんかつ|TONKATSU|돈가스)', '일식당', '음식점', '돈까스 일반 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(사보텐|카츠야|마이센|기소야|카츠&)', '일식당', '음식점', '돈까스 전문 브랜드 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(경양식|일본식돈까스|왕돈까스|치즈돈까스|카레돈까스)', '일식당', '음식점', '돈까스 변형 메뉴 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(카츠동|카츠돈|かつ丼|가츠동|돈까스덮밥)', '일식당', '음식점', '카츠동 전문점 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(규동|규돈|牛丼|GYUDON|소고기덮밥)', '일식당', '음식점', '규동 전문점 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(요시노야|스키야|마츠야|나카우|규동전문)', '일식당', '음식점', '규동 체인점 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(덮밥|돈부리|どんぶり|DONBURI|일본덮밥)', '일식당', '음식점', '덮밥 일반 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(오야코동|親子丼|텐동|天丼|우나동|うな丼)', '일식당', '음식점', '특수 덮밥 종류 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(이자카야|居酒屋|IZAKAYA|일본술집|일본선술집)', '일식당', '음식점', '이자카야 일반 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(와라와라|츠보하치|토리돈|야키토리|꼬치구이)', '일식당', '음식점', '이자카야 브랜드 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(사케|日本酒|니혼슈|청주|일본술)', '일식당', '음식점', '일본술 전문점 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(야키니쿠|焼肉|YAKINIKU|일본식구이|화로구이)', '일식당', '음식점', '야키니쿠 전문점 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(규카츠|규가츠|牛カツ|소고기카츠|비프카츠)', '일식당', '음식점', '규카츠 전문점 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(텐푸라|덴뿌라|天ぷら|TEMPURA|튀김정식)', '일식당', '음식점', '텐푸라 전문점 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(장어|우나기|うなぎ|UNAGI|장어구이|장어덮밥)', '일식당', '음식점', '장어 전문점 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(스키야키|すき焼き|SUKIYAKI|일본식전골|샤브샤브)', '일식당', '음식점', '스키야키/샤브샤브 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(나베|鍋|NABE|일본전골|일본식찌개)', '일식당', '음식점', '나베 요리 전문점 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(벤토|弁当|BENTO|도시락|일본도시락)', '일식당', '음식점', '일본식 도시락 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(오코노미야키|お好み焼き|타코야키|たこ焼き|일본전)', '일식당', '음식점', '오코노미야키/타코야키 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(카레|카레라이스|カレー|CURRY|일본카레)', '일식당', '음식점', '일본 카레 전문점 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(코코이찌방야|CoCo壱番屋|아비꼬|카레신)', '일식당', '음식점', '카레 전문 브랜드 패턴', 85, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.85}'::jsonb),
  ('(미소시루|味噌汁|일본국|일본된장국)', '일식당', '음식점', '일본 국/찌개 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(정식|定食|TEISHOKU|일본정식|일식정식)', '일식당', '음식점', '일본 정식 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(야마야|오오토야|혼케츠루하시|후라토식당)', '일식당', '음식점', '일본 정식당 브랜드 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(모찌|떡|もち|MOCHI|일본떡)', '일식당', '음식점', '일본 떡/디저트 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(와규|和牛|WAGYU|일본소|일본한우)', '일식당', '음식점', '와규 전문점 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(참치|마구로|まぐろ|TUNA|참치전문)', '일식당', '음식점', '참치 전문점 패턴', 80, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.8}'::jsonb),
  ('(연어|사케|サケ|SALMON|연어전문)', '일식당', '음식점', '연어 전문점 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(카이센동|海鮮丼|해산물덮밥|회덮밥)', '일식당', '음식점', '카이센동 전문점 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(치라시|ちらし|CHIRASHI|치라시스시|흩뿌림초밥)', '일식당', '음식점', '치라시 전문점 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(마키|巻き|MAKI|김밥초밥|롤초밥)', '일식당', '음식점', '마키/롤 전문점 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(니기리|握り|NIGIRI|쥔초밥|손초밥)', '일식당', '음식점', '니기리 전문점 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(가이세키|懐石|KAISEKI|일본코스요리|고급일식)', '일식당', '음식점', '가이세키 요리 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb),
  ('(로바타야키|炉端焼|화로구이|일본숯불구이)', '일식당', '음식점', '로바타야키 전문점 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(멘타이코|明太子|명란|명란젓|멘타이)', '일식당', '음식점', '멘타이코 요리 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(에비|海老|새우튀김|새우카츠|에비후라이)', '일식당', '음식점', '새우 요리 전문점 패턴', 70, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.7}'::jsonb),
  ('(일본가정식|일본집밥|오카상|엄마손맛|일본홈쿠킹)', '일식당', '음식점', '일본 가정식 패턴', 75, '{"source": "json_conversion", "original_category": "음식점", "confidence": 0.75}'::jsonb)
) AS t(pattern, replacement, category, description, priority, metadata);

-- 중복되지 않는 규칙만 삽입
INSERT INTO regex_preprocessing_rules (pattern, replacement, category, description, priority, is_active, created_at, updated_at, metadata)
SELECT 
  t.pattern,
  t.replacement, 
  t.category,
  t.description,
  t.priority,
  t.is_active,
  t.created_at,
  t.updated_at,
  t.metadata
FROM temp_new_rules t
WHERE NOT EXISTS (
  SELECT 1 FROM regex_preprocessing_rules r 
  WHERE r.pattern = t.pattern
);

-- 통계 출력
SELECT 
  'JSON 변환 완료' as status,
  COUNT(*) as new_rules_added
FROM regex_preprocessing_rules 
WHERE metadata->>'source' = 'json_conversion';

SELECT 
  category,
  COUNT(*) as rule_count
FROM regex_preprocessing_rules 
WHERE metadata->>'source' = 'json_conversion'
GROUP BY category
ORDER BY rule_count DESC;