import React from 'react';
import {
  View,
  Text,
  StyleSheet,
  TouchableOpacity,
  Animated,
  Alert
} from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { Swipeable } from 'react-native-gesture-handler';
import { JournalEntry } from '../../services/BookkeepingService';

interface JournalEntryCardProps {
  entry: JournalEntry;
  onPress: () => void;
  onApprove?: () => void;
  onEdit?: () => void;
  onDelete?: () => void;
}

const JournalEntryCard: React.FC<JournalEntryCardProps> = ({
  entry,
  onPress,
  onApprove,
  onEdit,
  onDelete
}) => {
  const getStatusColor = (status: string) => {
    switch (status) {
      case 'DRAFT':
        return '#F59E0B';
      case 'CONFIRMED':
        return '#3B82F6';
      case 'POSTED':
        return '#10B981';
      default:
        return '#6B7280';
    }
  };

  const getStatusText = (status: string) => {
    switch (status) {
      case 'DRAFT':
        return '검토 필요';
      case 'CONFIRMED':
        return '승인됨';
      case 'POSTED':
        return '완료됨';
      default:
        return status;
    }
  };

  const getConfidenceColor = (confidence: number) => {
    if (confidence >= 90) return '#10B981';
    if (confidence >= 70) return '#F59E0B';
    return '#EF4444';
  };

  const formatAmount = (amount: number) => {
    return `₩${amount.toLocaleString()}`;
  };

  const formatDate = (dateString: string) => {
    const date = new Date(dateString);
    return date.toLocaleDateString('ko-KR', {
      month: 'short',
      day: 'numeric'
    });
  };

  const renderRightActions = () => {
    const actions = [];

    if (entry.status === 'DRAFT' && onApprove) {
      actions.push(
        <TouchableOpacity
          key="approve"
          style={[styles.actionButton, { backgroundColor: '#10B981' }]}
          onPress={() => {
            Alert.alert(
              '분개 승인',
              '이 분개를 승인하시겠습니까?',
              [
                { text: '취소', style: 'cancel' },
                { text: '승인', onPress: onApprove }
              ]
            );
          }}
        >
          <Ionicons name="checkmark" size={20} color="white" />
          <Text style={styles.actionText}>승인</Text>
        </TouchableOpacity>
      );
    }

    if (onEdit) {
      actions.push(
        <TouchableOpacity
          key="edit"
          style={[styles.actionButton, { backgroundColor: '#3B82F6' }]}
          onPress={onEdit}
        >
          <Ionicons name="pencil" size={20} color="white" />
          <Text style={styles.actionText}>수정</Text>
        </TouchableOpacity>
      );
    }

    if (onDelete && entry.status === 'DRAFT') {
      actions.push(
        <TouchableOpacity
          key="delete"
          testID="delete-button"
          style={[styles.actionButton, { backgroundColor: '#EF4444' }]}
          onPress={() => {
            Alert.alert(
              '분개 삭제',
              '이 분개를 삭제하시겠습니까?',
              [
                { text: '취소', style: 'cancel' },
                { text: '삭제', style: 'destructive', onPress: onDelete }
              ]
            );
          }}
        >
          <Ionicons name="trash" size={20} color="white" />
          <Text style={styles.actionText}>삭제</Text>
        </TouchableOpacity>
      );
    }

    return (
      <View style={styles.actionsContainer}>
        {actions}
      </View>
    );
  };

  return (
    <Swipeable renderRightActions={renderRightActions}>
      <TouchableOpacity style={styles.container} onPress={onPress} activeOpacity={0.7}>
        <View style={styles.header}>
          <View style={styles.leftHeader}>
            <Text style={styles.entryId}>#{entry.id}</Text>
            <View style={[styles.statusBadge, { backgroundColor: `${getStatusColor(entry.status)}15` }]}>
              <Text style={[styles.statusText, { color: getStatusColor(entry.status) }]}>
                {getStatusText(entry.status)}
              </Text>
            </View>
          </View>
          
          <View style={styles.rightHeader}>
            <Text style={styles.date}>{formatDate(entry.entryDate)}</Text>
            {entry.autoGenerated && (
              <View style={styles.aiIndicator}>
                <Ionicons name="flash" size={12} color="#8B5CF6" />
                <Text style={styles.aiText}>AI</Text>
              </View>
            )}
          </View>
        </View>

        <Text style={styles.description} numberOfLines={2}>
          {entry.description}
        </Text>

        <View style={styles.details}>
          <Text style={styles.amount}>{formatAmount(entry.totalAmount)}</Text>
          <View style={styles.detailsRight}>
            {entry.confidence && (
              <View style={styles.confidenceContainer} testID="confidence-indicator">
                <View
                  style={[
                    styles.confidenceDot,
                    { backgroundColor: getConfidenceColor(entry.confidence) }
                  ]}
                />
                <Text style={styles.confidenceText}>{entry.confidence}%</Text>
              </View>
            )}
            {entry.details && (
              <Text style={styles.lineCount}>{entry.details.length} 라인</Text>
            )}
          </View>
        </View>

        {/* Journal Entry Preview */}
        {entry.details && entry.details.length > 0 && (
          <View style={styles.preview}>
            <View style={styles.previewLine}>
              <Text style={styles.previewAccount} numberOfLines={1}>
                차변: {entry.details.find(d => d.debitAmount > 0)?.accountName}
              </Text>
              <Text style={styles.previewAmount}>
                ₩{entry.details.find(d => d.debitAmount > 0)?.debitAmount.toLocaleString()}
              </Text>
            </View>
            <View style={styles.previewLine}>
              <Text style={styles.previewAccount} numberOfLines={1}>
                대변: {entry.details.find(d => d.creditAmount > 0)?.accountName}
              </Text>
              <Text style={styles.previewAmount}>
                ₩{entry.details.find(d => d.creditAmount > 0)?.creditAmount.toLocaleString()}
              </Text>
            </View>
          </View>
        )}

        {/* Balance Check Indicator */}
        {entry.details && (
          <View style={styles.balanceIndicator} testID="balance-indicator">
            {(() => {
              const totalDebit = entry.details?.reduce((sum, detail) => sum + detail.debitAmount, 0) || 0;
              const totalCredit = entry.details?.reduce((sum, detail) => sum + detail.creditAmount, 0) || 0;
              const isBalanced = totalDebit === totalCredit;
              
              if (!isBalanced) {
                return (
                  <View testID="imbalance-warning" style={styles.imbalanceWarning}>
                    <Ionicons name="warning" size={14} color="#EF4444" />
                    <Text style={styles.imbalanceText}>불균형</Text>
                  </View>
                );
              }
              
              return (
                <>
                  <Ionicons
                    name="shield-checkmark"
                    size={14}
                    color="#10B981"
                    testID="status-icon"
                  />
                  <Text style={styles.balanceText}>대차평균</Text>
                </>
              );
            })()}
          </View>
        )}
      </TouchableOpacity>
    </Swipeable>
  );
};

const styles = StyleSheet.create({
  container: {
    backgroundColor: 'white',
    marginVertical: 4,
    borderRadius: 12,
    padding: 16,
    
    // Shadow for iOS
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    
    // Shadow for Android
    elevation: 2,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  leftHeader: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  rightHeader: {
    alignItems: 'flex-end',
  },
  entryId: {
    fontSize: 14,
    fontWeight: '600',
    color: '#374151',
    marginRight: 8,
  },
  statusBadge: {
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 6,
  },
  statusText: {
    fontSize: 11,
    fontWeight: '600',
  },
  date: {
    fontSize: 12,
    color: '#6B7280',
    marginBottom: 2,
  },
  aiIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#8B5CF615',
    paddingHorizontal: 4,
    paddingVertical: 1,
    borderRadius: 4,
  },
  aiText: {
    fontSize: 10,
    color: '#8B5CF6',
    fontWeight: '500',
    marginLeft: 2,
  },
  description: {
    fontSize: 14,
    color: '#1F2937',
    lineHeight: 20,
    marginBottom: 12,
  },
  details: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  amount: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#1F2937',
  },
  detailsRight: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  confidenceContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 12,
  },
  confidenceDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    marginRight: 4,
  },
  confidenceText: {
    fontSize: 11,
    color: '#6B7280',
  },
  lineCount: {
    fontSize: 11,
    color: '#9CA3AF',
  },
  preview: {
    backgroundColor: '#F9FAFB',
    borderRadius: 6,
    padding: 8,
    marginBottom: 8,
  },
  previewLine: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 2,
  },
  previewAccount: {
    fontSize: 11,
    color: '#4B5563',
    flex: 1,
    marginRight: 8,
  },
  previewAmount: {
    fontSize: 11,
    color: '#1F2937',
    fontWeight: '500',
  },
  balanceIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-end',
  },
  balanceText: {
    fontSize: 10,
    color: '#10B981',
    marginLeft: 2,
  },
  imbalanceWarning: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  imbalanceText: {
    fontSize: 10,
    color: '#EF4444',
    marginLeft: 2,
  },
  actionsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  actionButton: {
    width: 60,
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 1,
  },
  actionText: {
    fontSize: 10,
    color: 'white',
    fontWeight: '500',
    marginTop: 2,
  },
});

export default JournalEntryCard;