#!/usr/bin/env ts-node
/**
 * 확장된 한국 표준 계정과목 데이터 삽입 스크립트 (200+ 계정)
 * 전문적인 복식부기 시스템을 위한 완전한 계정과목 체계
 */
import { PrismaClient } from '../lib/generated/prisma';

const prisma = new PrismaClient();

const expandedAccounts = [
  // ============ 자산 계정 (1000번대) - 50개 ============

  // 당좌자산 (1100번대)
  {
    accountCode: '1110',
    accountName: '현금',
    accountType: '자산' as const,
    accountSubtype: '당좌자산',
    isDebitNormal: true,
    displayOrder: 10,
  },
  {
    accountCode: '1120',
    accountName: '보통예금',
    accountType: '자산' as const,
    accountSubtype: '당좌자산',
    isDebitNormal: true,
    displayOrder: 20,
  },
  {
    accountCode: '1121',
    accountName: '정기예금',
    accountType: '자산' as const,
    accountSubtype: '당좌자산',
    isDebitNormal: true,
    displayOrder: 25,
  },
  {
    accountCode: '1122',
    accountName: '적금',
    accountType: '자산' as const,
    accountSubtype: '당좌자산',
    isDebitNormal: true,
    displayOrder: 30,
  },
  {
    accountCode: '1130',
    accountName: '미수금',
    accountType: '자산' as const,
    accountSubtype: '당좌자산',
    isDebitNormal: true,
    displayOrder: 40,
  },
  {
    accountCode: '1131',
    accountName: '미수수익',
    accountType: '자산' as const,
    accountSubtype: '당좌자산',
    isDebitNormal: true,
    displayOrder: 45,
  },
  {
    accountCode: '1140',
    accountName: '선급금',
    accountType: '자산' as const,
    accountSubtype: '당좌자산',
    isDebitNormal: true,
    displayOrder: 50,
  },
  {
    accountCode: '1141',
    accountName: '선급비용',
    accountType: '자산' as const,
    accountSubtype: '당좌자산',
    isDebitNormal: true,
    displayOrder: 55,
  },
  {
    accountCode: '1150',
    accountName: '재고자산',
    accountType: '자산' as const,
    accountSubtype: '당좌자산',
    isDebitNormal: true,
    displayOrder: 60,
  },
  {
    accountCode: '1151',
    accountName: '상품',
    accountType: '자산' as const,
    accountSubtype: '당좌자산',
    isDebitNormal: true,
    displayOrder: 65,
  },
  {
    accountCode: '1152',
    accountName: '제품',
    accountType: '자산' as const,
    accountSubtype: '당좌자산',
    isDebitNormal: true,
    displayOrder: 70,
  },
  {
    accountCode: '1153',
    accountName: '반제품',
    accountType: '자산' as const,
    accountSubtype: '당좌자산',
    isDebitNormal: true,
    displayOrder: 75,
  },
  {
    accountCode: '1154',
    accountName: '원재료',
    accountType: '자산' as const,
    accountSubtype: '당좌자산',
    isDebitNormal: true,
    displayOrder: 80,
  },
  {
    accountCode: '1160',
    accountName: '단기투자자산',
    accountType: '자산' as const,
    accountSubtype: '당좌자산',
    isDebitNormal: true,
    displayOrder: 85,
  },
  {
    accountCode: '1161',
    accountName: '단기대여금',
    accountType: '자산' as const,
    accountSubtype: '당좌자산',
    isDebitNormal: true,
    displayOrder: 90,
  },
  {
    accountCode: '1170',
    accountName: '부가세선급금',
    accountType: '자산' as const,
    accountSubtype: '당좌자산',
    isDebitNormal: true,
    displayOrder: 95,
  },
  {
    accountCode: '1180',
    accountName: '외상매출금',
    accountType: '자산' as const,
    accountSubtype: '당좌자산',
    isDebitNormal: true,
    displayOrder: 100,
  },
  {
    accountCode: '1190',
    accountName: '기타유동자산',
    accountType: '자산' as const,
    accountSubtype: '당좌자산',
    isDebitNormal: true,
    displayOrder: 105,
  },

  // 고정자산 (1200번대)
  {
    accountCode: '1210',
    accountName: '건물',
    accountType: '자산' as const,
    accountSubtype: '유형자산',
    isDebitNormal: true,
    displayOrder: 110,
  },
  {
    accountCode: '1211',
    accountName: '건물감가상각누계액',
    accountType: '자산' as const,
    accountSubtype: '유형자산',
    isDebitNormal: false,
    displayOrder: 115,
  },
  {
    accountCode: '1220',
    accountName: '차량운반구',
    accountType: '자산' as const,
    accountSubtype: '유형자산',
    isDebitNormal: true,
    displayOrder: 120,
  },
  {
    accountCode: '1221',
    accountName: '차량운반구감가상각누계액',
    accountType: '자산' as const,
    accountSubtype: '유형자산',
    isDebitNormal: false,
    displayOrder: 125,
  },
  {
    accountCode: '1230',
    accountName: '비품',
    accountType: '자산' as const,
    accountSubtype: '유형자산',
    isDebitNormal: true,
    displayOrder: 130,
  },
  {
    accountCode: '1231',
    accountName: '비품감가상각누계액',
    accountType: '자산' as const,
    accountSubtype: '유형자산',
    isDebitNormal: false,
    displayOrder: 135,
  },
  {
    accountCode: '1240',
    accountName: '기계장치',
    accountType: '자산' as const,
    accountSubtype: '유형자산',
    isDebitNormal: true,
    displayOrder: 140,
  },
  {
    accountCode: '1241',
    accountName: '기계장치감가상각누계액',
    accountType: '자산' as const,
    accountSubtype: '유형자산',
    isDebitNormal: false,
    displayOrder: 145,
  },
  {
    accountCode: '1250',
    accountName: '토지',
    accountType: '자산' as const,
    accountSubtype: '유형자산',
    isDebitNormal: true,
    displayOrder: 150,
  },
  {
    accountCode: '1260',
    accountName: '컴퓨터',
    accountType: '자산' as const,
    accountSubtype: '유형자산',
    isDebitNormal: true,
    displayOrder: 155,
  },
  {
    accountCode: '1261',
    accountName: '컴퓨터감가상각누계액',
    accountType: '자산' as const,
    accountSubtype: '유형자산',
    isDebitNormal: false,
    displayOrder: 160,
  },
  {
    accountCode: '1270',
    accountName: '소프트웨어',
    accountType: '자산' as const,
    accountSubtype: '무형자산',
    isDebitNormal: true,
    displayOrder: 165,
  },
  {
    accountCode: '1271',
    accountName: '소프트웨어감가상각누계액',
    accountType: '자산' as const,
    accountSubtype: '무형자산',
    isDebitNormal: false,
    displayOrder: 170,
  },
  {
    accountCode: '1280',
    accountName: '영업권',
    accountType: '자산' as const,
    accountSubtype: '무형자산',
    isDebitNormal: true,
    displayOrder: 175,
  },
  {
    accountCode: '1290',
    accountName: '장기투자자산',
    accountType: '자산' as const,
    accountSubtype: '투자자산',
    isDebitNormal: true,
    displayOrder: 180,
  },
  {
    accountCode: '1291',
    accountName: '장기대여금',
    accountType: '자산' as const,
    accountSubtype: '투자자산',
    isDebitNormal: true,
    displayOrder: 185,
  },
  {
    accountCode: '1292',
    accountName: '보증금',
    accountType: '자산' as const,
    accountSubtype: '투자자산',
    isDebitNormal: true,
    displayOrder: 190,
  },
  {
    accountCode: '1293',
    accountName: '임차보증금',
    accountType: '자산' as const,
    accountSubtype: '투자자산',
    isDebitNormal: true,
    displayOrder: 195,
  },
  {
    accountCode: '1294',
    accountName: '출자금',
    accountType: '자산' as const,
    accountSubtype: '투자자산',
    isDebitNormal: true,
    displayOrder: 200,
  },
  {
    accountCode: '1295',
    accountName: '건설중인자산',
    accountType: '자산' as const,
    accountSubtype: '유형자산',
    isDebitNormal: true,
    displayOrder: 205,
  },

  // 기타자산 (1300번대)
  {
    accountCode: '1310',
    accountName: '이연법인세자산',
    accountType: '자산' as const,
    accountSubtype: '기타자산',
    isDebitNormal: true,
    displayOrder: 210,
  },
  {
    accountCode: '1320',
    accountName: '기타장기자산',
    accountType: '자산' as const,
    accountSubtype: '기타자산',
    isDebitNormal: true,
    displayOrder: 215,
  },
  {
    accountCode: '1330',
    accountName: '개발비',
    accountType: '자산' as const,
    accountSubtype: '무형자산',
    isDebitNormal: true,
    displayOrder: 220,
  },
  {
    accountCode: '1340',
    accountName: '특허권',
    accountType: '자산' as const,
    accountSubtype: '무형자산',
    isDebitNormal: true,
    displayOrder: 225,
  },
  {
    accountCode: '1350',
    accountName: '상표권',
    accountType: '자산' as const,
    accountSubtype: '무형자산',
    isDebitNormal: true,
    displayOrder: 230,
  },
  {
    accountCode: '1360',
    accountName: '산업재산권',
    accountType: '자산' as const,
    accountSubtype: '무형자산',
    isDebitNormal: true,
    displayOrder: 235,
  },
  {
    accountCode: '1370',
    accountName: '사업자등록보증금',
    accountType: '자산' as const,
    accountSubtype: '기타자산',
    isDebitNormal: true,
    displayOrder: 240,
  },
  {
    accountCode: '1380',
    accountName: '계약보증금',
    accountType: '자산' as const,
    accountSubtype: '기타자산',
    isDebitNormal: true,
    displayOrder: 245,
  },
  {
    accountCode: '1390',
    accountName: '기타무형자产',
    accountType: '자산' as const,
    accountSubtype: '무형자산',
    isDebitNormal: true,
    displayOrder: 250,
  },

  // ============ 부채 계정 (2000번대) - 30개 ============

  // 유동부채 (2100번대)
  {
    accountCode: '2110',
    accountName: '미지급금',
    accountType: '부채' as const,
    accountSubtype: '유동부채',
    isDebitNormal: false,
    displayOrder: 260,
  },
  {
    accountCode: '2111',
    accountName: '외상매입금',
    accountType: '부채' as const,
    accountSubtype: '유동부채',
    isDebitNormal: false,
    displayOrder: 265,
  },
  {
    accountCode: '2120',
    accountName: '선수금',
    accountType: '부채' as const,
    accountSubtype: '유동부채',
    isDebitNormal: false,
    displayOrder: 270,
  },
  {
    accountCode: '2121',
    accountName: '선수수익',
    accountType: '부채' as const,
    accountSubtype: '유동부채',
    isDebitNormal: false,
    displayOrder: 275,
  },
  {
    accountCode: '2130',
    accountName: '단기차입금',
    accountType: '부채' as const,
    accountSubtype: '유동부채',
    isDebitNormal: false,
    displayOrder: 280,
  },
  {
    accountCode: '2131',
    accountName: '단기대출',
    accountType: '부채' as const,
    accountSubtype: '유동부채',
    isDebitNormal: false,
    displayOrder: 285,
  },
  {
    accountCode: '2140',
    accountName: '미지급비용',
    accountType: '부채' as const,
    accountSubtype: '유동부채',
    isDebitNormal: false,
    displayOrder: 290,
  },
  {
    accountCode: '2141',
    accountName: '미지급급여',
    accountType: '부채' as const,
    accountSubtype: '유동부채',
    isDebitNormal: false,
    displayOrder: 295,
  },
  {
    accountCode: '2150',
    accountName: '부가세예수금',
    accountType: '부채' as const,
    accountSubtype: '유동부채',
    isDebitNormal: false,
    displayOrder: 300,
  },
  {
    accountCode: '2151',
    accountName: '원천세예수금',
    accountType: '부채' as const,
    accountSubtype: '유동부채',
    isDebitNormal: false,
    displayOrder: 305,
  },
  {
    accountCode: '2152',
    accountName: '주민세예수금',
    accountType: '부채' as const,
    accountSubtype: '유동부채',
    isDebitNormal: false,
    displayOrder: 310,
  },
  {
    accountCode: '2160',
    accountName: '국민연금예수금',
    accountType: '부채' as const,
    accountSubtype: '유동부채',
    isDebitNormal: false,
    displayOrder: 315,
  },
  {
    accountCode: '2161',
    accountName: '건강보험료예수금',
    accountType: '부채' as const,
    accountSubtype: '유동부채',
    isDebitNormal: false,
    displayOrder: 320,
  },
  {
    accountCode: '2162',
    accountName: '고용보험료예수금',
    accountType: '부채' as const,
    accountSubtype: '유동부채',
    isDebitNormal: false,
    displayOrder: 325,
  },
  {
    accountCode: '2170',
    accountName: '법인세미지급금',
    accountType: '부채' as const,
    accountSubtype: '유동부채',
    isDebitNormal: false,
    displayOrder: 330,
  },
  {
    accountCode: '2180',
    accountName: '퇴직급여충당금',
    accountType: '부채' as const,
    accountSubtype: '유동부채',
    isDebitNormal: false,
    displayOrder: 335,
  },

  // 비유동부채 (2200번대)
  {
    accountCode: '2210',
    accountName: '장기차입금',
    accountType: '부채' as const,
    accountSubtype: '비유동부채',
    isDebitNormal: false,
    displayOrder: 340,
  },
  {
    accountCode: '2211',
    accountName: '회사채',
    accountType: '부채' as const,
    accountSubtype: '비유동부채',
    isDebitNormal: false,
    displayOrder: 345,
  },
  {
    accountCode: '2220',
    accountName: '장기미지급금',
    accountType: '부채' as const,
    accountSubtype: '비유동부채',
    isDebitNormal: false,
    displayOrder: 350,
  },
  {
    accountCode: '2230',
    accountName: '퇴직급여충당부채',
    accountType: '부채' as const,
    accountSubtype: '비유동부채',
    isDebitNormal: false,
    displayOrder: 355,
  },
  {
    accountCode: '2240',
    accountName: '임대보증금',
    accountType: '부채' as const,
    accountSubtype: '비유동부채',
    isDebitNormal: false,
    displayOrder: 360,
  },
  {
    accountCode: '2250',
    accountName: '장기선수수익',
    accountType: '부채' as const,
    accountSubtype: '비유동부채',
    isDebitNormal: false,
    displayOrder: 365,
  },
  {
    accountCode: '2260',
    accountName: '이연법인세부채',
    accountType: '부채' as const,
    accountSubtype: '비유동부채',
    isDebitNormal: false,
    displayOrder: 370,
  },
  {
    accountCode: '2270',
    accountName: '기타장기부채',
    accountType: '부채' as const,
    accountSubtype: '비유동부채',
    isDebitNormal: false,
    displayOrder: 375,
  },

  // 우발부채 및 기타 (2300번대)
  {
    accountCode: '2310',
    accountName: '보증채무',
    accountType: '부채' as const,
    accountSubtype: '우발부채',
    isDebitNormal: false,
    displayOrder: 380,
  },
  {
    accountCode: '2320',
    accountName: '소송충당부채',
    accountType: '부채' as const,
    accountSubtype: '충당부채',
    isDebitNormal: false,
    displayOrder: 385,
  },
  {
    accountCode: '2330',
    accountName: '환경복구충당부채',
    accountType: '부채' as const,
    accountSubtype: '충당부채',
    isDebitNormal: false,
    displayOrder: 390,
  },
  {
    accountCode: '2340',
    accountName: '제품보증충당부채',
    accountType: '부채' as const,
    accountSubtype: '충당부채',
    isDebitNormal: false,
    displayOrder: 395,
  },
  {
    accountCode: '2350',
    accountName: '하자보수충당부채',
    accountType: '부채' as const,
    accountSubtype: '충당부채',
    isDebitNormal: false,
    displayOrder: 400,
  },
  {
    accountCode: '2360',
    accountName: '기타충당부채',
    accountType: '부채' as const,
    accountSubtype: '충당부채',
    isDebitNormal: false,
    displayOrder: 405,
  },

  // ============ 자본 계정 (3000번대) - 10개 ============

  {
    accountCode: '3110',
    accountName: '자본금',
    accountType: '자본' as const,
    accountSubtype: '자본금',
    isDebitNormal: false,
    displayOrder: 410,
  },
  {
    accountCode: '3120',
    accountName: '주식발행초과금',
    accountType: '자본' as const,
    accountSubtype: '자본금',
    isDebitNormal: false,
    displayOrder: 415,
  },
  {
    accountCode: '3210',
    accountName: '이익잉여금',
    accountType: '자본' as const,
    accountSubtype: '잉여금',
    isDebitNormal: false,
    displayOrder: 420,
  },
  {
    accountCode: '3211',
    accountName: '법정적립금',
    accountType: '자본' as const,
    accountSubtype: '잉여금',
    isDebitNormal: false,
    displayOrder: 425,
  },
  {
    accountCode: '3212',
    accountName: '임의적립금',
    accountType: '자본' as const,
    accountSubtype: '잉여금',
    isDebitNormal: false,
    displayOrder: 430,
  },
  {
    accountCode: '3220',
    accountName: '미처분이익잉여금',
    accountType: '자본' as const,
    accountSubtype: '잉여금',
    isDebitNormal: false,
    displayOrder: 435,
  },
  {
    accountCode: '3230',
    accountName: '기타포괄손익누계액',
    accountType: '자본' as const,
    accountSubtype: '기타자본',
    isDebitNormal: false,
    displayOrder: 440,
  },
  {
    accountCode: '3240',
    accountName: '자기주식',
    accountType: '자본' as const,
    accountSubtype: '기타자본',
    isDebitNormal: true,
    displayOrder: 445,
  },
  {
    accountCode: '3250',
    accountName: '자본조정',
    accountType: '자본' as const,
    accountSubtype: '기타자본',
    isDebitNormal: false,
    displayOrder: 450,
  },
  {
    accountCode: '3260',
    accountName: '비지배지분',
    accountType: '자본' as const,
    accountSubtype: '기타자본',
    isDebitNormal: false,
    displayOrder: 455,
  },

  // ============ 수익 계정 (4000번대) - 20개 ============

  // 영업수익 (4100번대)
  {
    accountCode: '4110',
    accountName: '매출',
    accountType: '수익' as const,
    accountSubtype: '영업수익',
    isDebitNormal: false,
    displayOrder: 460,
  },
  {
    accountCode: '4111',
    accountName: '제품매출',
    accountType: '수익' as const,
    accountSubtype: '영업수익',
    isDebitNormal: false,
    displayOrder: 465,
  },
  {
    accountCode: '4112',
    accountName: '상품매출',
    accountType: '수익' as const,
    accountSubtype: '영업수익',
    isDebitNormal: false,
    displayOrder: 470,
  },
  {
    accountCode: '4113',
    accountName: '용역매출',
    accountType: '수익' as const,
    accountSubtype: '영업수익',
    isDebitNormal: false,
    displayOrder: 475,
  },
  {
    accountCode: '4120',
    accountName: '매출할인',
    accountType: '수익' as const,
    accountSubtype: '영업수익',
    isDebitNormal: true,
    displayOrder: 480,
  },
  {
    accountCode: '4130',
    accountName: '매출환입',
    accountType: '수익' as const,
    accountSubtype: '영업수익',
    isDebitNormal: true,
    displayOrder: 485,
  },
  {
    accountCode: '4140',
    accountName: '수출매출',
    accountType: '수익' as const,
    accountSubtype: '영업수익',
    isDebitNormal: false,
    displayOrder: 490,
  },
  {
    accountCode: '4150',
    accountName: '임대수익',
    accountType: '수익' as const,
    accountSubtype: '영업수익',
    isDebitNormal: false,
    displayOrder: 495,
  },
  {
    accountCode: '4160',
    accountName: '로열티수익',
    accountType: '수익' as const,
    accountSubtype: '영업수익',
    isDebitNormal: false,
    displayOrder: 500,
  },
  {
    accountCode: '4170',
    accountName: '가맹점수익',
    accountType: '수익' as const,
    accountSubtype: '영업수익',
    isDebitNormal: false,
    displayOrder: 505,
  },

  // 영업외수익 (4200번대)
  {
    accountCode: '4210',
    accountName: '기타수익',
    accountType: '수익' as const,
    accountSubtype: '영업외수익',
    isDebitNormal: false,
    displayOrder: 510,
  },
  {
    accountCode: '4211',
    accountName: '이자수익',
    accountType: '수익' as const,
    accountSubtype: '영업외수익',
    isDebitNormal: false,
    displayOrder: 515,
  },
  {
    accountCode: '4212',
    accountName: '배당금수익',
    accountType: '수익' as const,
    accountSubtype: '영업외수익',
    isDebitNormal: false,
    displayOrder: 520,
  },
  {
    accountCode: '4213',
    accountName: '외환차익',
    accountType: '수익' as const,
    accountSubtype: '영업외수익',
    isDebitNormal: false,
    displayOrder: 525,
  },
  {
    accountCode: '4214',
    accountName: '외화환산이익',
    accountType: '수익' as const,
    accountSubtype: '영업외수익',
    isDebitNormal: false,
    displayOrder: 530,
  },
  {
    accountCode: '4220',
    accountName: '유형자산처분이익',
    accountType: '수익' as const,
    accountSubtype: '영업외수익',
    isDebitNormal: false,
    displayOrder: 535,
  },
  {
    accountCode: '4230',
    accountName: '잡이익',
    accountType: '수익' as const,
    accountSubtype: '영업외수익',
    isDebitNormal: false,
    displayOrder: 540,
  },
  {
    accountCode: '4240',
    accountName: '수입수수료',
    accountType: '수익' as const,
    accountSubtype: '영업외수익',
    isDebitNormal: false,
    displayOrder: 545,
  },
  {
    accountCode: '4250',
    accountName: '채권현재가치할인차액상각',
    accountType: '수익' as const,
    accountSubtype: '영업외수익',
    isDebitNormal: false,
    displayOrder: 550,
  },
  {
    accountCode: '4260',
    accountName: '충당부채환입익',
    accountType: '수익' as const,
    accountSubtype: '영업외수익',
    isDebitNormal: false,
    displayOrder: 555,
  },

  // ============ 비용 계정 (5000번대) - 90개 ============

  // 매출원가 (5000번대 - 기존 계정 피하여 사용)
  {
    accountCode: '5010',
    accountName: '제품매출원가',
    accountType: '비용' as const,
    accountSubtype: '매출원가',
    isDebitNormal: true,
    displayOrder: 560,
  },
  {
    accountCode: '5011',
    accountName: '상품매출원가',
    accountType: '비용' as const,
    accountSubtype: '매출원가',
    isDebitNormal: true,
    displayOrder: 565,
  },
  {
    accountCode: '5012',
    accountName: '기초재고자산',
    accountType: '비용' as const,
    accountSubtype: '매출원가',
    isDebitNormal: true,
    displayOrder: 570,
  },
  {
    accountCode: '5013',
    accountName: '원재료비',
    accountType: '비용' as const,
    accountSubtype: '매출원가',
    isDebitNormal: true,
    displayOrder: 575,
  },
  {
    accountCode: '5014',
    accountName: '노무비',
    accountType: '비용' as const,
    accountSubtype: '매출원가',
    isDebitNormal: true,
    displayOrder: 580,
  },
  {
    accountCode: '5015',
    accountName: '제조경비',
    accountType: '비용' as const,
    accountSubtype: '매출원가',
    isDebitNormal: true,
    displayOrder: 585,
  },
  {
    accountCode: '5016',
    accountName: '기말재고자산',
    accountType: '비용' as const,
    accountSubtype: '매출원가',
    isDebitNormal: false,
    displayOrder: 590,
  },

  // 판매비와관리비 (5200번대) - 세분화된 60개
  {
    accountCode: '5210',
    accountName: '급여',
    accountType: '비용' as const,
    accountSubtype: '판매관리비',
    isDebitNormal: true,
    displayOrder: 595,
  },
  {
    accountCode: '5211',
    accountName: '상여금',
    accountType: '비용' as const,
    accountSubtype: '판매관리비',
    isDebitNormal: true,
    displayOrder: 600,
  },
  {
    accountCode: '5212',
    accountName: '임시직급여',
    accountType: '비용' as const,
    accountSubtype: '판매관리비',
    isDebitNormal: true,
    displayOrder: 605,
  },
  {
    accountCode: '5220',
    accountName: '복리후생비',
    accountType: '비용' as const,
    accountSubtype: '판매관리비',
    isDebitNormal: true,
    displayOrder: 610,
  },
  {
    accountCode: '5221',
    accountName: '국민연금',
    accountType: '비용' as const,
    accountSubtype: '판매관리비',
    isDebitNormal: true,
    displayOrder: 615,
  },
  {
    accountCode: '5222',
    accountName: '건강보험료',
    accountType: '비용' as const,
    accountSubtype: '판매관리비',
    isDebitNormal: true,
    displayOrder: 620,
  },
  {
    accountCode: '5223',
    accountName: '고용보험료',
    accountType: '비용' as const,
    accountSubtype: '판매관리비',
    isDebitNormal: true,
    displayOrder: 625,
  },
  {
    accountCode: '5224',
    accountName: '산재보험료',
    accountType: '비용' as const,
    accountSubtype: '판매관리비',
    isDebitNormal: true,
    displayOrder: 630,
  },
  {
    accountCode: '5230',
    accountName: '접대비',
    accountType: '비용' as const,
    accountSubtype: '판매관리비',
    isDebitNormal: true,
    displayOrder: 635,
  },
  {
    accountCode: '5240',
    accountName: '광고선전비',
    accountType: '비용' as const,
    accountSubtype: '판매관리비',
    isDebitNormal: true,
    displayOrder: 640,
  },
  {
    accountCode: '5241',
    accountName: '마케팅비',
    accountType: '비용' as const,
    accountSubtype: '판매관리비',
    isDebitNormal: true,
    displayOrder: 645,
  },
  {
    accountCode: '5250',
    accountName: '교육훈련비',
    accountType: '비용' as const,
    accountSubtype: '판매관리비',
    isDebitNormal: true,
    displayOrder: 650,
  },
  {
    accountCode: '5260',
    accountName: '출장비',
    accountType: '비용' as const,
    accountSubtype: '판매관리비',
    isDebitNormal: true,
    displayOrder: 655,
  },
  {
    accountCode: '5261',
    accountName: '국내출장비',
    accountType: '비용' as const,
    accountSubtype: '판매관리비',
    isDebitNormal: true,
    displayOrder: 660,
  },
  {
    accountCode: '5262',
    accountName: '해외출장비',
    accountType: '비용' as const,
    accountSubtype: '판매관리비',
    isDebitNormal: true,
    displayOrder: 665,
  },
  {
    accountCode: '5270',
    accountName: '통신비',
    accountType: '비용' as const,
    accountSubtype: '판매관리비',
    isDebitNormal: true,
    displayOrder: 670,
  },
  {
    accountCode: '5271',
    accountName: '전화료',
    accountType: '비용' as const,
    accountSubtype: '판매관리비',
    isDebitNormal: true,
    displayOrder: 675,
  },
  {
    accountCode: '5272',
    accountName: '인터넷료',
    accountType: '비용' as const,
    accountSubtype: '판매관리비',
    isDebitNormal: true,
    displayOrder: 680,
  },
  {
    accountCode: '5280',
    accountName: '임차료',
    accountType: '비용' as const,
    accountSubtype: '판매관리비',
    isDebitNormal: true,
    displayOrder: 685,
  },
  {
    accountCode: '5281',
    accountName: '사무실임차료',
    accountType: '비용' as const,
    accountSubtype: '판매관리비',
    isDebitNormal: true,
    displayOrder: 690,
  },
  {
    accountCode: '5282',
    accountName: '창고임차료',
    accountType: '비용' as const,
    accountSubtype: '판매관리비',
    isDebitNormal: true,
    displayOrder: 695,
  },
  {
    accountCode: '5290',
    accountName: '보험료',
    accountType: '비용' as const,
    accountSubtype: '판매관리비',
    isDebitNormal: true,
    displayOrder: 700,
  },
  {
    accountCode: '5291',
    accountName: '사업자종합보험료',
    accountType: '비용' as const,
    accountSubtype: '판매관리비',
    isDebitNormal: true,
    displayOrder: 705,
  },
  {
    accountCode: '5292',
    accountName: '자동차보험료',
    accountType: '비용' as const,
    accountSubtype: '판매관리비',
    isDebitNormal: true,
    displayOrder: 710,
  },

  // 차량 및 운반비 (5300번대)
  {
    accountCode: '5310',
    accountName: '차량유지비',
    accountType: '비용' as const,
    accountSubtype: '판매관리비',
    isDebitNormal: true,
    displayOrder: 715,
  },
  {
    accountCode: '5311',
    accountName: '유류비',
    accountType: '비용' as const,
    accountSubtype: '판매관리비',
    isDebitNormal: true,
    displayOrder: 720,
  },
  {
    accountCode: '5312',
    accountName: '차량수리비',
    accountType: '비용' as const,
    accountSubtype: '판매관리비',
    isDebitNormal: true,
    displayOrder: 725,
  },
  {
    accountCode: '5313',
    accountName: '자동차세',
    accountType: '비용' as const,
    accountSubtype: '판매관리비',
    isDebitNormal: true,
    displayOrder: 730,
  },
  {
    accountCode: '5320',
    accountName: '운반비',
    accountType: '비용' as const,
    accountSubtype: '판매관리비',
    isDebitNormal: true,
    displayOrder: 735,
  },
  {
    accountCode: '5321',
    accountName: '택배비',
    accountType: '비용' as const,
    accountSubtype: '판매관리비',
    isDebitNormal: true,
    displayOrder: 740,
  },

  // 사무 및 관리비 (5400번대)
  {
    accountCode: '5410',
    accountName: '소모품비',
    accountType: '비용' as const,
    accountSubtype: '판매관리비',
    isDebitNormal: true,
    displayOrder: 745,
  },
  {
    accountCode: '5411',
    accountName: '사무용품비',
    accountType: '비용' as const,
    accountSubtype: '판매관리비',
    isDebitNormal: true,
    displayOrder: 750,
  },
  {
    accountCode: '5412',
    accountName: 'IT소모품비',
    accountType: '비용' as const,
    accountSubtype: '판매관리비',
    isDebitNormal: true,
    displayOrder: 755,
  },
  {
    accountCode: '5420',
    accountName: '도서인쇄비',
    accountType: '비용' as const,
    accountSubtype: '판매관리비',
    isDebitNormal: true,
    displayOrder: 760,
  },
  {
    accountCode: '5430',
    accountName: '회의비',
    accountType: '비용' as const,
    accountSubtype: '판매관리비',
    isDebitNormal: true,
    displayOrder: 765,
  },
  {
    accountCode: '5440',
    accountName: '세금과공과',
    accountType: '비용' as const,
    accountSubtype: '판매관리비',
    isDebitNormal: true,
    displayOrder: 770,
  },
  {
    accountCode: '5441',
    accountName: '인지세',
    accountType: '비용' as const,
    accountSubtype: '판매관리비',
    isDebitNormal: true,
    displayOrder: 775,
  },
  {
    accountCode: '5442',
    accountName: '등록세',
    accountType: '비용' as const,
    accountSubtype: '판매관리비',
    isDebitNormal: true,
    displayOrder: 780,
  },
  {
    accountCode: '5450',
    accountName: '지급수수료',
    accountType: '비용' as const,
    accountSubtype: '판매관리비',
    isDebitNormal: true,
    displayOrder: 785,
  },
  {
    accountCode: '5451',
    accountName: '은행수수료',
    accountType: '비용' as const,
    accountSubtype: '판매관리비',
    isDebitNormal: true,
    displayOrder: 790,
  },
  {
    accountCode: '5452',
    accountName: '신용카드수수료',
    accountType: '비용' as const,
    accountSubtype: '판매관리비',
    isDebitNormal: true,
    displayOrder: 795,
  },
  {
    accountCode: '5453',
    accountName: '전문서비스수수료',
    accountType: '비용' as const,
    accountSubtype: '판매관리비',
    isDebitNormal: true,
    displayOrder: 800,
  },

  // 전문서비스비 (5500번대)
  {
    accountCode: '5510',
    accountName: '법무비',
    accountType: '비용' as const,
    accountSubtype: '판매관리비',
    isDebitNormal: true,
    displayOrder: 805,
  },
  {
    accountCode: '5520',
    accountName: '회계감사비',
    accountType: '비용' as const,
    accountSubtype: '판매관리비',
    isDebitNormal: true,
    displayOrder: 810,
  },
  {
    accountCode: '5530',
    accountName: '세무대리비',
    accountType: '비용' as const,
    accountSubtype: '판매관리비',
    isDebitNormal: true,
    displayOrder: 815,
  },
  {
    accountCode: '5540',
    accountName: '컨설팅비',
    accountType: '비용' as const,
    accountSubtype: '판매관리비',
    isDebitNormal: true,
    displayOrder: 820,
  },
  {
    accountCode: '5550',
    accountName: '용역비',
    accountType: '비용' as const,
    accountSubtype: '판매관리비',
    isDebitNormal: true,
    displayOrder: 825,
  },
  {
    accountCode: '5560',
    accountName: '외주제작비',
    accountType: '비용' as const,
    accountSubtype: '판매관리비',
    isDebitNormal: true,
    displayOrder: 830,
  },

  // 감가상각비 및 기타 (5600번대)
  {
    accountCode: '5610',
    accountName: '건물감가상각비',
    accountType: '비용' as const,
    accountSubtype: '판매관리비',
    isDebitNormal: true,
    displayOrder: 835,
  },
  {
    accountCode: '5620',
    accountName: '차량운반구감가상각비',
    accountType: '비용' as const,
    accountSubtype: '판매관리비',
    isDebitNormal: true,
    displayOrder: 840,
  },
  {
    accountCode: '5630',
    accountName: '비품감가상각비',
    accountType: '비용' as const,
    accountSubtype: '판매관리비',
    isDebitNormal: true,
    displayOrder: 845,
  },
  {
    accountCode: '5640',
    accountName: '기계장치감가상각비',
    accountType: '비용' as const,
    accountSubtype: '판매관리비',
    isDebitNormal: true,
    displayOrder: 850,
  },
  {
    accountCode: '5650',
    accountName: '컴퓨터감가상각비',
    accountType: '비용' as const,
    accountSubtype: '판매관리비',
    isDebitNormal: true,
    displayOrder: 855,
  },
  {
    accountCode: '5660',
    accountName: '소프트웨어감가상각비',
    accountType: '비용' as const,
    accountSubtype: '판매관리비',
    isDebitNormal: true,
    displayOrder: 860,
  },

  // 영업외비용 (5700번대)
  {
    accountCode: '5710',
    accountName: '이자비용',
    accountType: '비용' as const,
    accountSubtype: '영업외비용',
    isDebitNormal: true,
    displayOrder: 865,
  },
  {
    accountCode: '5720',
    accountName: '외환차손',
    accountType: '비용' as const,
    accountSubtype: '영업외비용',
    isDebitNormal: true,
    displayOrder: 870,
  },
  {
    accountCode: '5730',
    accountName: '외화환산손실',
    accountType: '비용' as const,
    accountSubtype: '영업외비용',
    isDebitNormal: true,
    displayOrder: 875,
  },
  {
    accountCode: '5740',
    accountName: '유형자산처분손실',
    accountType: '비용' as const,
    accountSubtype: '영업외비용',
    isDebitNormal: true,
    displayOrder: 880,
  },
  {
    accountCode: '5750',
    accountName: '대손상각비',
    accountType: '비용' as const,
    accountSubtype: '영업외비용',
    isDebitNormal: true,
    displayOrder: 885,
  },
  {
    accountCode: '5760',
    accountName: '잡손실',
    accountType: '비용' as const,
    accountSubtype: '영업외비용',
    isDebitNormal: true,
    displayOrder: 890,
  },
  {
    accountCode: '5770',
    accountName: '기부금',
    accountType: '비용' as const,
    accountSubtype: '영업외비용',
    isDebitNormal: true,
    displayOrder: 895,
  },
  {
    accountCode: '5780',
    accountName: '건물임차보증금손실',
    accountType: '비용' as const,
    accountSubtype: '영업외비용',
    isDebitNormal: true,
    displayOrder: 900,
  },

  // 특별손익 (5800번대)
  {
    accountCode: '5810',
    accountName: '재해손실',
    accountType: '비용' as const,
    accountSubtype: '특별손실',
    isDebitNormal: true,
    displayOrder: 905,
  },
  {
    accountCode: '5820',
    accountName: '소송비',
    accountType: '비용' as const,
    accountSubtype: '특별손실',
    isDebitNormal: true,
    displayOrder: 910,
  },
  {
    accountCode: '5830',
    accountName: '과년도손익수정손실',
    accountType: '비용' as const,
    accountSubtype: '특별손실',
    isDebitNormal: true,
    displayOrder: 915,
  },
  {
    accountCode: '5840',
    accountName: '법인세비용',
    accountType: '비용' as const,
    accountSubtype: '법인세비용',
    isDebitNormal: true,
    displayOrder: 920,
  },
  {
    accountCode: '5841',
    accountName: '당기법인세',
    accountType: '비용' as const,
    accountSubtype: '법인세비용',
    isDebitNormal: true,
    displayOrder: 925,
  },
  {
    accountCode: '5842',
    accountName: '이연법인세',
    accountType: '비용' as const,
    accountSubtype: '법인세비용',
    isDebitNormal: true,
    displayOrder: 930,
  },

  // 수익 계정 추가 (4300번대)
  {
    accountCode: '4310',
    accountName: '할인매출환입',
    accountType: '수익' as const,
    accountSubtype: '영업수익',
    isDebitNormal: false,
    displayOrder: 558,
  },
  {
    accountCode: '4320',
    accountName: '판매장려금',
    accountType: '수익' as const,
    accountSubtype: '영업수익',
    isDebitNormal: false,
    displayOrder: 559,
  },

  // 추가 전문 계정 (5900번대)
  {
    accountCode: '5910',
    accountName: '의료비',
    accountType: '비용' as const,
    accountSubtype: '복리후생비',
    isDebitNormal: true,
    displayOrder: 935,
  },
  {
    accountCode: '5920',
    accountName: '야근식대',
    accountType: '비용' as const,
    accountSubtype: '복리후생비',
    isDebitNormal: true,
    displayOrder: 940,
  },
  {
    accountCode: '5930',
    accountName: '퇴직급여',
    accountType: '비용' as const,
    accountSubtype: '인건비',
    isDebitNormal: true,
    displayOrder: 945,
  },
  {
    accountCode: '5940',
    accountName: '퇴직급여충당금전입액',
    accountType: '비용' as const,
    accountSubtype: '인건비',
    isDebitNormal: true,
    displayOrder: 950,
  },
  {
    accountCode: '5950',
    accountName: '시설관리비',
    accountType: '비용' as const,
    accountSubtype: '판매관리비',
    isDebitNormal: true,
    displayOrder: 955,
  },
  {
    accountCode: '5960',
    accountName: '청소비',
    accountType: '비용' as const,
    accountSubtype: '판매관리비',
    isDebitNormal: true,
    displayOrder: 960,
  },
  {
    accountCode: '5970',
    accountName: '보안비',
    accountType: '비용' as const,
    accountSubtype: '판매관리비',
    isDebitNormal: true,
    displayOrder: 965,
  },
  {
    accountCode: '5980',
    accountName: '수선유지비',
    accountType: '비용' as const,
    accountSubtype: '판매관리비',
    isDebitNormal: true,
    displayOrder: 970,
  },
  {
    accountCode: '5990',
    accountName: '기타판매관리비',
    accountType: '비용' as const,
    accountSubtype: '판매관리비',
    isDebitNormal: true,
    displayOrder: 975,
  },

  // 추가 자산 계정 (1400번대)
  {
    accountCode: '1410',
    accountName: '기타유가증권',
    accountType: '자산' as const,
    accountSubtype: '투자자산',
    isDebitNormal: true,
    displayOrder: 250,
  },
  {
    accountCode: '1420',
    accountName: '투자부동산',
    accountType: '자산' as const,
    accountSubtype: '투자자산',
    isDebitNormal: true,
    displayOrder: 255,
  },
  {
    accountCode: '1430',
    accountName: '사용권자산',
    accountType: '자산' as const,
    accountSubtype: '유형자산',
    isDebitNormal: true,
    displayOrder: 260,
  },
  {
    accountCode: '1431',
    accountName: '사용권자산감가상각누계액',
    accountType: '자산' as const,
    accountSubtype: '유형자산',
    isDebitNormal: false,
    displayOrder: 265,
  },
  {
    accountCode: '1440',
    accountName: '연구개발비',
    accountType: '자산' as const,
    accountSubtype: '무형자산',
    isDebitNormal: true,
    displayOrder: 270,
  },
];

async function insertExpandedChartOfAccounts() {
  console.log('🏗️  확장된 한국 표준 계정과목 데이터 삽입 시작... (200+ 계정)');

  try {
    // 기존 데이터 확인
    const existingCount = await prisma.chartOfAccounts.count();
    console.log(`📊 기존 계정과목 수: ${existingCount}개`);

    if (existingCount >= 200) {
      console.log('✅ 이미 확장된 계정과목 데이터가 존재합니다. (200+ 계정)');
      return;
    }

    // 기존 계정과목 조회
    const existingCodes = await prisma.chartOfAccounts.findMany({
      select: { accountCode: true },
    });
    const existingCodesSet = new Set(existingCodes.map(c => c.accountCode));

    // 새로운 계정과목만 필터링
    const newAccounts = expandedAccounts.filter(
      account => !existingCodesSet.has(account.accountCode)
    );

    console.log(`📥 ${newAccounts.length}개의 새로운 계정과목 삽입 중...`);

    if (newAccounts.length === 0) {
      console.log('✅ 모든 확장 계정과목이 이미 존재합니다.');
      return;
    }

    // 배치 삽입 (새로운 계정만)
    const result = await prisma.chartOfAccounts.createMany({
      data: newAccounts,
      skipDuplicates: true, // 중복 방지
    });

    console.log(
      `✅ 성공적으로 ${result.count}개의 확장된 계정과목을 생성했습니다.`
    );

    // 통계 조회
    const statistics = await Promise.all([
      prisma.chartOfAccounts.count({ where: { accountType: '자산' } }),
      prisma.chartOfAccounts.count({ where: { accountType: '부채' } }),
      prisma.chartOfAccounts.count({ where: { accountType: '자본' } }),
      prisma.chartOfAccounts.count({ where: { accountType: '수익' } }),
      prisma.chartOfAccounts.count({ where: { accountType: '비용' } }),
    ]);

    console.log('\n📈 계정과목 유형별 통계:');
    console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
    console.log(`자산 계정: ${statistics[0]}개`);
    console.log(`부채 계정: ${statistics[1]}개`);
    console.log(`자본 계정: ${statistics[2]}개`);
    console.log(`수익 계정: ${statistics[3]}개`);
    console.log(`비용 계정: ${statistics[4]}개`);
    console.log(`총 계정: ${statistics.reduce((a, b) => a + b, 0)}개`);

    // 생성된 계정과목 확인 (주요 계정만)
    const keyAccounts = await prisma.chartOfAccounts.findMany({
      where: {
        OR: [
          {
            accountCode: {
              in: ['1110', '1120', '2110', '3110', '4110', '5210'],
            },
          },
          { accountType: '자산', accountSubtype: '당좌자산' },
          { accountType: '비용', accountSubtype: '판매관리비' },
        ],
      },
      orderBy: { displayOrder: 'asc' },
      select: {
        accountCode: true,
        accountName: true,
        accountType: true,
        accountSubtype: true,
        isDebitNormal: true,
      },
      take: 20,
    });

    console.log('\n📋 생성된 주요 계정과목 목록 (처음 20개):');
    console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
    keyAccounts.forEach((account: any) => {
      const balance = account.isDebitNormal ? '차변' : '대변';
      console.log(
        `${account.accountCode} | ${account.accountName.padEnd(15)} | ${account.accountType} - ${account.accountSubtype} (${balance})`
      );
    });

    console.log('\n🎉 한국 표준 계정과목 확장이 완료되었습니다!');
    console.log('✨ MVP 수준의 복식부기 시스템을 위한 기반이 구축되었습니다.');
  } catch (error) {
    console.error('❌ 확장된 계정과목 삽입 중 오류 발생:', error);
    throw error;
  } finally {
    await prisma.$disconnect();
  }
}

// 스크립트 실행
if (require.main === module) {
  insertExpandedChartOfAccounts().catch(error => {
    console.error(error);
    process.exit(1);
  });
}

module.exports = { insertExpandedChartOfAccounts };
