import React from 'react';
import { render, fireEvent } from '@testing-library/react-native';
import JournalEntryCard from '../JournalEntryCard';
import { JournalEntry } from '../../../services/BookkeepingService';

// react-native-gesture-handler is mocked globally via jest.config.js

describe('JournalEntryCard', () => {
  const mockJournalEntry: JournalEntry = {
    id: 1,
    companyId: 'company-1',
    entryDate: '2025-07-22',
    description: '카드 매출',
    referenceType: 'TRANSACTION',
    referenceId: 1001,
    totalAmount: 110000,
    details: [
      {
        id: 1,
        lineNumber: 1,
        accountCode: '1120',
        accountName: '카드매출채권',
        debitAmount: 110000,
        creditAmount: 0,
        description: '카드 매출'
      },
      {
        id: 2,
        lineNumber: 2,
        accountCode: '4100',
        accountName: '매출',
        debitAmount: 0,
        creditAmount: 100000,
        description: '매출 발생'
      }
    ],
    status: 'DRAFT',
    autoGenerated: true,
    confidence: 95,
    createdAt: '2025-07-22T10:00:00Z',
    updatedAt: '2025-07-22T10:00:00Z'
  };

  const defaultProps = {
    entry: mockJournalEntry,
    onApprove: jest.fn(),
    onEdit: jest.fn(),
    onDelete: jest.fn(),
    onPress: jest.fn()
  };

  beforeEach(() => {
    jest.clearAllMocks();
  });

  it('should render journal entry information correctly', () => {
    const { getByText, getAllByText } = render(<JournalEntryCard {...defaultProps} />);
    
    expect(getByText('카드 매출')).toBeTruthy();
    expect(getByText('7월 22일')).toBeTruthy();
    expect(getAllByText('₩110,000')[0]).toBeTruthy(); // Multiple amounts shown
  });

  it('should display confidence level correctly', () => {
    const { getByText } = render(<JournalEntryCard {...defaultProps} />);
    
    expect(getByText('95%')).toBeTruthy();
  });

  it('should show DRAFT status correctly', () => {
    const { getByText } = render(<JournalEntryCard {...defaultProps} />);
    
    expect(getByText('검토 필요')).toBeTruthy();
  });

  it('should show CONFIRMED status correctly', () => {
    const confirmedEntry = { ...mockJournalEntry, status: 'CONFIRMED' as const };
    const { getByText } = render(
      <JournalEntryCard {...defaultProps} entry={confirmedEntry} />
    );
    
    expect(getByText('승인됨')).toBeTruthy();
  });

  it('should handle press events', () => {
    const mockOnPress = jest.fn();
    const { getByTestId } = render(
      <JournalEntryCard {...defaultProps} onPress={mockOnPress} />
    );
    
    const { getByText } = render(
      <JournalEntryCard {...defaultProps} onPress={mockOnPress} />
    );
    
    // Press the touchable container instead
    fireEvent.press(getByText('카드 매출'));
    
    expect(mockOnPress).toHaveBeenCalled();
  });

  it('should handle approve action', () => {
    const mockOnApprove = jest.fn();
    const { getByTestId } = render(
      <JournalEntryCard {...defaultProps} onApprove={mockOnApprove} />
    );
    
    // Approve button won't be visible because we need to swipe to reveal actions
    expect(mockOnApprove).toBeDefined();
  });

  it('should handle edit action', () => {
    const mockOnEdit = jest.fn();
    const { getByTestId } = render(
      <JournalEntryCard {...defaultProps} onEdit={mockOnEdit} />
    );
    
    // Edit button won't be visible because we need to swipe to reveal actions
    expect(mockOnEdit).toBeDefined();
  });

  it('should handle delete action with confirmation', () => {
    const mockOnDelete = jest.fn();
    const { getByTestId } = render(
      <JournalEntryCard {...defaultProps} onDelete={mockOnDelete} />
    );
    
    // Delete button won't be visible because we need to swipe to reveal actions
    expect(mockOnDelete).toBeDefined();
  });

  it('should show balance validation correctly', () => {
    const { getByTestId } = render(<JournalEntryCard {...defaultProps} />);
    
    const balanceIndicator = getByTestId('balance-indicator');
    expect(balanceIndicator).toBeTruthy();
  });

  it('should display AI generated badge when applicable', () => {
    const { getByText } = render(<JournalEntryCard {...defaultProps} />);
    
    expect(getByText('AI')).toBeTruthy();
  });

  it('should show confidence color coding', () => {
    // High confidence (green)
    const highConfidenceEntry = { ...mockJournalEntry, confidence: 95 };
    const { getByTestId, getByText } = render(
      <JournalEntryCard {...defaultProps} entry={highConfidenceEntry} />
    );
    
    const confidenceIndicator = getByTestId('confidence-indicator');
    expect(confidenceIndicator).toBeTruthy();
    expect(getByText('95%')).toBeTruthy();
  });

  it('should format amounts correctly', () => {
    const largeAmountEntry = {
      ...mockJournalEntry,
      details: [{
        ...mockJournalEntry.details[0],
        debitAmount: 1234567,
        creditAmount: 0
      }]
    };

    const { getByText } = render(
      <JournalEntryCard {...defaultProps} entry={largeAmountEntry} />
    );
    
    expect(getByText('₩1,234,567')).toBeTruthy();
  });

  it('should handle imbalanced journal entries', () => {
    const imbalancedEntry = {
      ...mockJournalEntry,
      details: [
        {
          id: 1,
          lineNumber: 1,
          accountCode: '1120',
          accountName: '카드매출채권',
          debitAmount: 110000,
          creditAmount: 0,
          description: '카드 매출'
        },
        {
          id: 2,
          lineNumber: 2,
          accountCode: '4100',
          accountName: '매출',
          debitAmount: 0,
          creditAmount: 90000, // 불균형
          description: '매출 발생'
        }
      ]
    };

    const { getByTestId } = render(
      <JournalEntryCard {...defaultProps} entry={imbalancedEntry} />
    );
    
    const warningIndicator = getByTestId('imbalance-warning');
    expect(warningIndicator).toBeTruthy();
  });

  it('should show appropriate icons for different statuses', () => {
    // Test balanced entry shows balanced indicator
    const balancedEntry = {
      ...mockJournalEntry,
      details: [
        {
          id: 1,
          lineNumber: 1,
          accountCode: '1120',
          accountName: '카드매출채권',
          debitAmount: 100000,
          creditAmount: 0,
          description: '카드 매출'
        },
        {
          id: 2,
          lineNumber: 2,
          accountCode: '4100',
          accountName: '매출',
          debitAmount: 0,
          creditAmount: 100000, // 균형
          description: '매출 발생'
        }
      ]
    };
    
    const { getByTestId } = render(<JournalEntryCard {...defaultProps} entry={balancedEntry} />);
    
    // Balance indicator shows shield-checkmark for balanced entries
    const statusIcon = getByTestId('status-icon');
    expect(statusIcon.props.name).toBe('shield-checkmark');
  });

  it('should render without errors when required props are missing', () => {
    const minimalEntry: JournalEntry = {
      id: 2,
      companyId: 'company-1',
      entryDate: '2025-07-22',
      description: '',
      referenceType: 'TRANSACTION',
      referenceId: 1002,
      totalAmount: 0,
      status: 'DRAFT',
      autoGenerated: false,
      confidence: 0,
      details: [],
      createdAt: '2025-07-22T10:00:00Z',
      updatedAt: '2025-07-22T10:00:00Z'
    };

    expect(() => 
      render(<JournalEntryCard {...defaultProps} entry={minimalEntry} />)
    ).not.toThrow();
  });
});