import bookkeepingReducer, {
  processTransaction,
  fetchJournalEntries,
  updateJournalEntry,
  BookkeepingState
} from '../bookkeepingSlice';
import { JournalEntry, JournalEntryDetail } from '../../../services/BookkeepingService';
import { configureStore } from '@reduxjs/toolkit';

import BookkeepingService from '../../../services/BookkeepingService';

// Mock BookkeepingService methods
jest.spyOn(BookkeepingService, 'generateJournalEntry').mockImplementation();
jest.spyOn(BookkeepingService, 'getJournalEntries').mockImplementation();
jest.spyOn(BookkeepingService, 'updateJournalEntry').mockImplementation();
jest.spyOn(BookkeepingService, 'deleteJournalEntry').mockImplementation();

describe('bookkeepingSlice', () => {
  const mockJournalEntry: JournalEntry = {
    id: 1,
    companyId: 'company-1',
    entryDate: '2025-07-22',
    description: '테스트 분개',
    referenceType: 'TRANSACTION',
    referenceId: 1001,
    totalAmount: 100000,
    status: 'DRAFT',
    autoGenerated: true,
    confidence: 95,
    details: [
      {
        id: 1,
        lineNumber: 1,
        accountCode: '1120',
        accountName: '보통예금',
        debitAmount: 100000,
        creditAmount: 0,
        description: '매출 입금'
      },
      {
        id: 2,
        lineNumber: 2,
        accountCode: '4110',
        accountName: '매출',
        debitAmount: 0,
        creditAmount: 100000,
        description: '매출 발생'
      }
    ],
    createdAt: '2025-07-22T10:00:00Z',
    updatedAt: '2025-07-22T10:00:00Z'
  };

  const initialState: BookkeepingState = {
    journalEntries: [],
    currentJournalEntry: null,
    chartOfAccounts: [],
    
    isLoadingJournalEntries: false,
    isProcessingTransaction: false,
    isUpdatingJournalEntry: false,
    isLoadingChartOfAccounts: false,
    
    error: null,
    processError: null,
    
    filters: {
      status: 'ALL',
      startDate: '2025-07-01',
      endDate: '2025-07-31',
      companyId: 'company-1'
    },
    
    stats: {
      totalEntries: 0,
      pendingReview: 0,
      completedToday: 0,
      errorEntries: 0,
      totalAmount: 0
    }
  };

  describe('reducers', () => {
    it('should return initial state', () => {
      const state = bookkeepingReducer(undefined, { type: 'unknown' });
      // Check the important fields, but skip dynamic date fields
      expect(state.journalEntries).toEqual([]);
      expect(state.currentJournalEntry).toBeNull();
      expect(state.chartOfAccounts).toEqual([]);
      expect(state.isLoadingJournalEntries).toBe(false);
      expect(state.isProcessingTransaction).toBe(false);
      expect(state.error).toBeNull();
      expect(state.filters.status).toBe('ALL');
      expect(state.stats.totalEntries).toBe(0);
    });

    it('should handle initial state correctly', () => {
      expect(initialState.journalEntries).toEqual([]);
      expect(initialState.currentJournalEntry).toBeNull();
      expect(initialState.isProcessingTransaction).toBe(false);
    });
  });

  describe('async thunks', () => {
    let store: any;

    beforeEach(() => {
      store = configureStore({
        reducer: {
          bookkeeping: bookkeepingReducer,
        },
      });
      jest.clearAllMocks();
    });

    describe('processTransaction', () => {
      it('should handle successful transaction processing', async () => {
        const mockResponse = {
          success: true,
          journalEntry: mockJournalEntry,
          processingInfo: {
            processingTimeMs: 150,
            method: 'AI_GENERATED',
            ruleSource: 'DEFAULT'
          }
        };

        (BookkeepingService.generateJournalEntry as jest.Mock).mockResolvedValue(mockResponse);

        const request = {
          transactionId: 1001,
          companyId: 'company-1',
          forceRegenerate: false
        };

        await store.dispatch(processTransaction(request));

        const state = store.getState().bookkeeping;
        expect(state.isProcessingTransaction).toBe(false);
        expect(BookkeepingService.generateJournalEntry).toHaveBeenCalledWith(request);
      });

      it('should handle transaction processing failure', async () => {
        const mockResponse = {
          success: false,
          message: 'Transaction processing failed',
          error: 'Invalid transaction data'
        };

        (BookkeepingService.generateJournalEntry as jest.Mock).mockResolvedValue(mockResponse);

        const request = {
          transactionId: 1001,
          companyId: 'company-1'
        };

        await store.dispatch(processTransaction(request));

        const state = store.getState().bookkeeping;
        expect(state.isProcessingTransaction).toBe(false);
        expect(state.processError).not.toBeNull();
      });
    });

    describe('fetchJournalEntries', () => {
      it('should fetch journal entries successfully', async () => {
        const mockEntries = [mockJournalEntry];

        (BookkeepingService.getJournalEntries as jest.Mock).mockResolvedValue(mockEntries);

        await store.dispatch(fetchJournalEntries({
          companyId: 'company-1',
          startDate: '2025-07-01',
          endDate: '2025-07-31'
        }));

        const state = store.getState().bookkeeping;
        expect(state.isLoadingJournalEntries).toBe(false);
        expect(BookkeepingService.getJournalEntries).toHaveBeenCalledWith(
          'company-1',
          '2025-07-01',
          '2025-07-31'
        );
      });
    });
  });
});