import BookkeepingService, { 
  JournalEntry, 
  JournalEntryDetail, 
  TransactionToJournalRequest,
  JournalEntryResponse 
} from '../BookkeepingService';

// Mock fetch globally
global.fetch = jest.fn();
const mockFetch = global.fetch as jest.MockedFunction<typeof fetch>;

describe('BookkeepingService', () => {
  beforeEach(() => {
    mockFetch.mockClear();
  });

  const mockJournalEntry: JournalEntry = {
    id: 1,
    companyId: 'company-1',
    entryDate: '2025-07-22',
    description: '테스트 분개',
    referenceType: 'TRANSACTION',
    referenceId: 1001,
    totalAmount: 100000,
    status: 'DRAFT',
    autoGenerated: true,
    confidence: 95,
    details: [
      {
        id: 1,
        lineNumber: 1,
        accountCode: '1100',
        accountName: '현금',
        debitAmount: 100000,
        creditAmount: 0,
        description: '현금 입금'
      },
      {
        id: 2,
        lineNumber: 2,
        accountCode: '4100',
        accountName: '매출',
        debitAmount: 0,
        creditAmount: 100000,
        description: '매출 발생'
      }
    ],
    createdAt: '2025-07-22T10:00:00Z',
    updatedAt: '2025-07-22T10:00:00Z'
  };

  describe('validateJournalEntry', () => {
    it('should return balanced=true when debits equal credits', () => {
      const validation = BookkeepingService.validateJournalEntry(mockJournalEntry);
      
      expect(validation.isBalanced).toBe(true);
      expect(validation.totalDebit).toBe(100000);
      expect(validation.totalCredit).toBe(100000);
      expect(validation.errors).toHaveLength(0);
    });

    it('should return balanced=false when debits do not equal credits', () => {
      const imbalancedEntry: JournalEntry = {
        ...mockJournalEntry,
        id: 2,
        details: [
          {
            id: 3,
            lineNumber: 1,
            accountCode: '1100',
            accountName: '현금',
            debitAmount: 100000,
            creditAmount: 0,
            description: '현금 입금'
          },
          {
            id: 4,
            lineNumber: 2,
            accountCode: '4100',
            accountName: '매출',
            debitAmount: 0,
            creditAmount: 90000, // 불균형
            description: '매출 발생'
          }
        ]
      };

      const validation = BookkeepingService.validateJournalEntry(imbalancedEntry);
      
      expect(validation.isBalanced).toBe(false);
      expect(validation.totalDebit).toBe(100000);
      expect(validation.totalCredit).toBe(90000);
      expect(validation.errors.length).toBeGreaterThan(0);
    });

    it('should validate empty details array', () => {
      const emptyEntry: JournalEntry = {
        ...mockJournalEntry,
        id: 3,
        details: []
      };

      const validation = BookkeepingService.validateJournalEntry(emptyEntry);
      
      expect(validation.isBalanced).toBe(false);
      expect(validation.totalDebit).toBe(0);
      expect(validation.totalCredit).toBe(0);
      expect(validation.errors.length).toBeGreaterThan(0);
    });
  });

  describe('generateJournalEntry', () => {
    it('should generate journal entry successfully', async () => {
      const mockResponse: JournalEntryResponse = {
        success: true,
        journalEntry: mockJournalEntry,
        validation: {
          isValid: true,
          balanceCheck: 'BALANCED',
          errorMessages: []
        },
        processingInfo: {
          processingTimeMs: 150,
          method: 'AI_GENERATED',
          ruleSource: 'DEFAULT'
        }
      };

      mockFetch.mockResolvedValueOnce({
        ok: true,
        json: async () => mockResponse
      } as Response);

      const request: TransactionToJournalRequest = {
        transactionId: 1001,
        companyId: 'company-1',
        forceRegenerate: false
      };

      const result = await BookkeepingService.generateJournalEntry(request);

      expect(result.success).toBe(true);
      expect(result.journalEntry).toEqual(mockJournalEntry);
      expect(mockFetch).toHaveBeenCalledWith(
        expect.stringContaining('/api/v2/accounting/process-transaction'),
        expect.objectContaining({
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify(request)
        })
      );
    });

    it('should handle API errors gracefully', async () => {
      mockFetch.mockResolvedValueOnce({
        ok: false,
        json: async () => ({ message: 'Invalid transaction data' })
      } as Response);

      const request: TransactionToJournalRequest = {
        transactionId: 1001,
        companyId: 'company-1'
      };

      const result = await BookkeepingService.generateJournalEntry(request);

      expect(result.success).toBe(false);
      expect(result.message).toBe('Invalid transaction data');
    });

    it('should handle network errors', async () => {
      mockFetch.mockRejectedValueOnce(new Error('Network error'));

      const request: TransactionToJournalRequest = {
        transactionId: 1001,
        companyId: 'company-1'
      };

      const result = await BookkeepingService.generateJournalEntry(request);

      expect(result.success).toBe(false);
      expect(result.message).toBe('네트워크 오류가 발생했습니다.');
      expect(result.error).toBe('Network error');
    });
  });

  describe('getJournalEntries', () => {
    it('should fetch journal entries successfully', async () => {
      const mockEntries = [mockJournalEntry];

      mockFetch.mockResolvedValueOnce({
        ok: true,
        json: async () => mockEntries
      } as Response);

      const result = await BookkeepingService.getJournalEntries(
        'company-1',
        '2025-07-01',
        '2025-07-31'
      );

      expect(result).toEqual(mockEntries);
      expect(mockFetch).toHaveBeenCalledWith(
        expect.stringContaining('/api/v2/accounting/journal-entries'),
        expect.objectContaining({
          method: 'GET'
        })
      );
    });

    it('should handle empty results', async () => {
      mockFetch.mockResolvedValueOnce({
        ok: true,
        json: async () => []
      } as Response);

      const result = await BookkeepingService.getJournalEntries(
        'company-1',
        '2025-07-01',
        '2025-07-31'
      );

      expect(result).toEqual([]);
    });
  });

  describe('updateJournalEntry', () => {
    it('should update journal entry successfully', async () => {
      const updatedEntry = {
        ...mockJournalEntry,
        description: '수정된 분개',
        status: 'CONFIRMED' as const
      };

      mockFetch.mockResolvedValueOnce({
        ok: true,
        json: async () => updatedEntry
      } as Response);

      const result = await BookkeepingService.updateJournalEntry(updatedEntry.id, updatedEntry);

      expect(result).toEqual({
        success: true,
        journalEntry: updatedEntry
      });
      expect(mockFetch).toHaveBeenCalledWith(
        expect.stringContaining(`/api/v2/accounting/journal-entry/${updatedEntry.id}`),
        expect.objectContaining({
          method: 'PUT',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify(updatedEntry)
        })
      );
    });
  });

  describe('deleteJournalEntry', () => {
    it('should delete journal entry successfully', async () => {
      mockFetch.mockResolvedValueOnce({
        ok: true,
        json: async () => ({ success: true })
      } as Response);

      const result = await BookkeepingService.deleteJournalEntry(1);

      expect(result).toEqual({ success: true });
      expect(mockFetch).toHaveBeenCalledWith(
        expect.stringContaining('/api/v2/accounting/journal-entries/1'),
        expect.objectContaining({
          method: 'DELETE'
        })
      );
    });
  });
});